import { lib, game, ui, get, ai, _status } from '../../noname.js'
import { globalskills } from "./skills/globalskills.js";
import { shiptypeskills } from "./skills/shiptypeskills.js";
import { standard } from "./skills/standard.js";
import { unfulfilledambition } from "./skills/unfulfilledambition.js";
import { historybattles } from "./skills/historybattles.js";
import { fallendemon } from "./skills/fallendemon.js";
import { cangqinghuanying } from './skills/cangqinghuanying.js';
import { shuileizhandui } from './skills/shuileizhandui.js';
import { others } from './skills/others.js';
var jianrjinji = {
    name: 'jianrjinji',//武将包命名（必填）
    connect: true,//该武将包是否可以联机（必填）,"xianjinld""zhiyangai","baiyin_skill",
    //全局技能"_yuanhang","_jianzaochuan","_qianghuazhuang",
    characterSort: {
        jianrjinji: {
            jianrbiaozhun: ["liekexingdun_R", "qixichicheng_R", "wufenzhongchicheng_R", "qiye_R", "bisimai_R", "misuli_R", "weineituo_R", "lisailiu_R", "1913_R", "changmen_R", "kunxi_R", "ougengqi_R", "qingye_R", "beianpudun_R", "jiujinshan_R", "yixian_R", "tianlangxing_R", "dadianrendian_R", "yatelanda_R", "z31_R", "xuefeng_R", "kangfusi_R", "47project_R", "guzhuyizhichuixue_R", "shuileizhanduichuixue_R", "mingsike_R", "yinghuochong_R", "u1405_R", "baiyanjuren_R", "changchun_R"],
            lishizhanyi_naerweike: ["shengwang_R", "z17_R", "z18_R", "z21_R", "z22_R", "gesakeren_R", "biaoqiang_R", "aisijimoren_R"],
            lishizhanyi_matapanjiao: ["kewei_R", "shengqiaozhi_R", "luodeni_R", "boerzanuo_R", "jialibodi_R"],
            lishizhanyi_danmaihaixia: ["hude_R", "shenluopujun_R", "weiershiqinwang_R", "z1_R", "z16_R"],
            lishizhanyi_shanhuhai: ["lafei_R", "shiyu_R", "salemu_R", "dahuangfeng_R", "yuekecheng_R", "qiuyue_R", "weilianDbote_R", "xianghe_R", "ruihe_R", "yuhei_R", "guying_R"],
            lishizhanyi_haixiafujizhan: ["u47_R", "u81_R", "u505_R", "jinqu_R", "kente_R", "u96_R", "lundun_R"],
            weijingzhizhi: ["jifu_R", "dujiaoshou_R", "sp_lafei_R", "getelan_R", "sp_aisaikesi_R", "sp_ninghai_R", "sp_zhongtudao_R", "xukufu_R", "lingbo_R", "kelaosaiweici_R", "gaobo_R", "sp_dading_R", "sp_shenxue_R", "deyizhiA59_R"],
            cangqinghuanying: ["mist_dujiaoshou_R", "mist_xiawu_R", "mist_shanhuhai_R"],
            shixinrumoR_tan: ["bismarck_R", "tirpitz_R", "akagikaga_R"],
            shixinrumoR_chen: ["401_R", "chaoyamato_R", "yamato_R"],
            shixinrumoR_chi: ["southdakota_R", "pachina_R", "loki_R"],
            shixinrumoR_man: ["sukhbaatar_R", "odin_R", "vestal_R"],
            shixinrumoR_yi: ["savoy_R", "cassone_R", "Xfliegerkorps_R"],
            others: ["boerzhanuo_R", "dafeng_R", "dajingbeishang_R", "jialifuniya_R", "ninghai_R", "nvzaoshen_R", "jiate_R", "rangbaer_R", "wugelini_R", "yaergushuishou_R", "yi25_R", "yiahua_R", "skilltest"],
            shuileizhandui: ["jiagu_R", "buzhihuo_R", "chuannei_R", "chuxue_R", "dian_R", "lei_R", "fubo_R", "shenxue_R", "wushiling_R", "xiangqu_R", "baixue_R", "xiao_R", "yangyan_R"],
        },
    },
    character: {
        liekexingdun_R: ["female", "USN", 4, ["hangmucv", "hangkongzhanshuxianqu"], ["zhu", "des:　由列克星敦级战列巡洋舰改装而来。1927年服役之后同姐妹舰萨拉托加号多次参加美国海军的各种演习,为航母的使用和发展积累了大量经验。日军偷袭珍珠港时列克星敦号因正向威克岛运输飞机而躲过一劫。1942年的珊瑚海海战中,列克星敦号击沉击伤日军航母各一艘,但自身也被日本航母重创,后因损管不利,油气爆炸而沉没。"]],
        qixichicheng_R: ["female", "IJN", 4, ["hangmucv", "qixi_cv"], ["zhu", "des:　原本是日本海军天城级战列巡洋舰2番舰,后因条约限制改建成为舰队航母。建成时拥有特别的三段飞行甲板,不过这个设计被证明并不实用。35年的大改装中拆除了这个不实用的设计,变为常见的全通飞行甲板。41年赤城号作为日军的旗舰参加了偷袭珍珠港。42年的中途岛海战中赤城号遭到企业号俯冲轰炸机的攻击,诱发了堆放的鱼雷和炸弹,次日由日军自沉。"]],
        wufenzhongchicheng_R: ["female", "IJN", 4, ["hangmucv", "mingyundewufenzhong"], ["des:　原本是日本海军天城级战列巡洋舰2番舰,后因条约限制改建成为舰队航母。建成时拥有特别的三段飞行甲板,不过这个设计被证明并不实用。35年的大改装中拆除了这个不实用的设计,变为常见的全通飞行甲板。41年赤城号作为日军的旗舰参加了偷袭珍珠港。42年的中途岛海战中赤城号遭到企业号俯冲轰炸机的攻击,诱发了堆放的鱼雷和炸弹,次日由日军自沉。"]],
        qiye_R: ["female", "USN", 4, ["hangmucv", "dajiaoduguibi", "dumuchenglin", "bigE"], ["des:　企业号是美国获得战斗之星最多的军舰,在42年的中途岛战役中,正是企业号的轰炸机摧毁了赤城、加贺以及飞龙。随后的圣克鲁斯海战中企业号被击伤,但企业号边修边走,放出的飞机空袭了比睿。在这次海战后,美军在太平洋上只剩下了企业号一艘舰队航母。这时期企业号挂起了一条史诗般的标语：企业单挑日本（Enterprise VS Japan）。在43年,企业号改造为最早搭载全天候战机的航母。莱特湾海战中,企业号是唯一对全部日本舰队都空袭过的航母。在击沉武藏号跟大和号的战斗中也有企业号的身影。"]],
        bisimai_R: ["female", "KMS", 4, ["zhuangjiafh", "zhanliebb", "qijianshashou", "yongbuchenmodezhanjian"], ["zhu", "des:德国于30年代建造的俾斯麦级战列舰首舰,建成之后连英国首相也称赞其是出色的设计。服役之后41年俾斯麦号在欧根亲王号的护航下前出大西洋执行破交任务,在战斗中俾斯麦号击沉了前来拦截的英国胡德号、击伤了威尔士亲王号。之后英国集结大规模兵力围歼俾斯麦号,战斗中皇家方舟号航母的剑鱼击伤了俾斯麦号的船舵,大大影响了俾斯麦号的航行,之后俾斯麦号在英国舰队的围攻下沉没。"]],
        misuli_R: ["female", "USN", 4, ["zhuangjiafh", "zhanliebb", "jueshengzhibing", "zhanfu"], ["des:密苏里是新锐衣阿华级战列舰的三号舰,衣阿华级沿用了南达级的防护设计,她装备了当时功率最大的动力系统,所以航速甚至比很多战巡还快。密苏里于45年才赶赴战场,并没有参加多少战斗,只是在45年3月被神风撞中一次,受损不大。让密苏里名垂青史的是日本投降签字仪式在她的甲板上举行,这代表了战争的正式结束。在冷战期间密苏里继续活跃,在80年代甚至重启并进行了导弹化改造,以符合现代海战的需要。91的海湾战争也是战列舰最后一次参加实战。在98年,密苏里作为纪念舰退役,她停泊在珍珠港,正前方正是亚利桑那博物馆,她们分别代表了战争的开始和结束。"]],
        weineituo_R: ["female", "RM", 3, ["zhuangjiafh", "zhanliebb", "yishisheji"], ["des:维内托级是意大利的新锐战列舰。该级的整体设计十分出色,值得称道的是381mm主炮的部分威力指标可以达到406mm炮水平。防护设计上,船体采用了普列赛水下防护系统,装甲使用倾斜多层的剥被帽设计。二战中,她在41年的马塔潘角海战中被鱼雷击伤,之后因为缺油不再出动。意大利投降后维内托号疏散到了马耳他,途中还曾被德军的制导炸弹击伤。维内托号最终幸存到了战后。"]],
        lisailiu_R: ["female", "MN", 4, ["zhuangjiafh", "zhanliebb", "kaixuan", "changge", "xiongjiaqibin"], ["des:黎塞留级是法国在30年代设计的新锐战列舰。该级依然沿袭敦刻尔克级的主炮全前置设计。40年,法国迅速战败,未完工的黎塞留号为了避免落入德军之手,于6月15日启航疏散到达喀尔。因惧怕处于流亡状态的六艘法国战列舰落入德国手中,英国舰队制定了名为“抛石机”的行动计划,对法国舰队进行了攻击。交火中黎塞留号被击伤,在此之后流亡非洲的法国舰队一直对战争局势持观望状态。42年黎塞留号同美国达成协议,加入同盟国作战。在美国进行改装后的黎塞留号参加了对日作战,并见证了二战的胜利。战后黎塞留号于1959年退役。"]],
        changmen_R: ["female", "IJN", 4, ["zhuangjiafh", "zhanliebb", "zhudaojiandui"], ["des:她与妹妹都是高火力型日本战列舰的代表,被称为海军假日七巨头之一。她建成时就有高大的六脚桅楼,可看做是日式高塔舰桥的开端。二战开始后,太平洋战场的形势变为航空主导。一直到44年的莱特湾海战,她才得到了一线作战的机会：她所在的栗田编队抓到了美军护航航母编队,但是在美军的拼命反抗下日军没能取得多大的战果。回到本土的她在搁置中迎来了日本投降。美军缴获之后将她用作“十字路口计划”核试验的靶船,于1946年7月沉没。"]],
        "1913_R": ["female", "ROCN", 4, ["zhuangjiafh", "zhanliebb", "jujianmengxiang"], ["zhu", "des:1913年时,为针对邻国的海军威胁,国民政府参谋部在海军造舰计划书中提出了颇为夸张的海军扩建计划,其中便包括大量的战列巡洋舰。该型战列巡洋所设想的性能参数为：排水量28000吨,装备10门14英寸火炮,航速29节左右。当然在那个穷困动荡的年代,海军意图获取主力舰无非是不切实际的妄想罢了……"]],
        kunxi_R: ["female", "USN", 4, ["huokongld", "zhongxunca", "gaosusheji"], ["des:新奥尔良级重巡洋舰6号舰。新奥尔良级是北安普顿级的改良版本,增强了防护。战争爆发后,昆西号先是执行了在大西洋的岛屿巡逻任务,后于42年5月通过巴拿马运河来到太平洋战场。在萨沃岛海战中,昆西号击中了鸟海号的舰桥,但是之后昆西号被日军集火射击,最终不幸被鱼雷击沉。"]],
        ougengqi_R: ["female", "KMS", 4, ["huokongld", "zhongxunca", "zhanxianfangyu"], ["des:希佩尔海军上将级重巡3号舰,有着不死鸟的绰号。相比前两艘,她的外形设计进行了一些改进。服役之后她同俾斯麦号一起行动参加了丹麦海峡海战,战斗结束后,她和俾斯麦号分头行动。俾斯麦号最终被击沉,而欧根亲王号则安全抵达法国。42年欧根亲王号同两艘沙恩霍斯特级执行了瑟布鲁斯行动,44年欧根亲王号在德军沿岸提供火力支援。战败后,欧根亲王号被赔偿给美国,在经历核试验和海洋风暴后,于拖拽过程中沉没。"]],
        qingye_R: ["female", "IJN", 4, ["huokongld", "zhongxunca", "sawohaizhan", "qingyeqingyeqing"], ["des:青叶型本属古鹰型的后续,但是由于修改了设计,所以这二艘被单独列为青叶型。在37年,青叶型进行了大规模改装。战争中青叶型和古鹰型编入同一部队作战,42年10月的海战中,青叶号将美军误认为友军,对美军打出“我是青叶”的信号,遭到了美军射击,在友舰的掩护下青叶号幸运逃脱,然而古鹰号却因此沉没。青叶号在44年遭到了潜艇袭击,返回日本修理之后不再出动,在坐沉中迎来了日本战败。"]],
        beianpudun_R: ["female", "USN", 4, ["huokongld", "zhongxunca", "huhangyuanhu"], ["des:北安普顿级是美国最早重巡彭萨科拉号的改进版本。在战争爆发后,北安普顿号参加了针对日军的报复性反击,这些反击行动极大鼓舞了美国的士气。北安普顿号主要被用于航母护航,在圣克鲁斯海战中,北安普顿号一度试图拖带受创的大黄蜂号,但由于日军不断的攻击而被迫放弃。在塔萨法隆加海战中北安普顿号被日军鱼雷击中沉没,由于损管和撤退有序,大部分舰员得以幸存。"]],
        jiujinshan_R: ["female", "USN", 4, ["huokongld", "zhongxunca", "jiujingzhanzhen"], ["des:旧金山号重巡洋舰属新奥尔良级重巡洋舰,和昆西等舰同级。旧金山号重巡洋舰作为旗舰参加了埃斯佩恩斯角海战。在第一次瓜岛海战中,旧金山依然担任舰队旗舰,尽管舰队指挥官牺牲,舰队损失较大,但是依然完成了拦截日军编队的任务,并重创比叡,导致其最终沉没。旧金山打满了战争全程,并获得了总统集体嘉奖。她17颗战役之星的获得数量仅次于企业和圣地亚哥。"]],
        yixian_R: ["female", "ROCN", 3, ["fangkong2", "qingxuncl", "shizhibuyu"], ["des:逸仙号是30年代中国自行设计建造的一艘巡洋舰。该舰从规格上讲只相当于列强的大型炮舰。抗战中,在宁海级相继殉国后逸仙号接替担任旗舰,在缺乏高射弹药的情况下,她曾经用前部150毫米主炮击落日本飞机。逸仙号最终不幸殉国,然而日本将其打捞修理使用,并一直幸存到了1945年。在抗战胜利后,这艘军舰又回归了中国,一直使用到了60年代。"]],
        tianlangxing_R: ["female", "RN", 3, ["fangkong2", "qingxuncl", "duomianshou"], ["des:属于黛朵级防空巡洋舰第二批,相比四座主炮的黛朵级第一批,第二批加强到了五座高平两用主炮,防空能力有所提升。天狼星完工后加入地中海舰队,参与了火炬行动,并见证了轴心国在北非投降,之后在地中海执行封锁任务。44年参与了诺曼底的支援行动,天狼星号在战后继续服役到了56年。"]],
        dadianrendian_R: ["female", "IJN", 3, ["fangkong2", "qingxuncl", "jilizhixin"], ["des:丙型巡洋舰设计要求有着很强的侦察和通讯能力。在早期的设计中,巡洋舰W105搭载有两座弹射器,全部集中在后部。舰载机除了机库外,两架系留于弹射器上。在W105阶段,丙型巡洋舰也并未强调对海火力,主要武器以127高炮为主。虽然一度考虑过鱼雷装备,但最终取消这个要求。W105案提交后,又增加了对海火力要求,安装之前巡洋舰拆下来的三联155主炮,这个设计最终演变为正式的丙型巡洋舰。"]],
        yatelanda_R: ["female", "USN", 3, ["fangkong2", "qingxuncl", "duikongfangyu"], ["des:　30年代末期设计的一级轻巡洋舰,最大特点是主炮数量极多,共安装了八座双联5吋炮。亚特兰大级初衷是作为驱逐舰旗舰使用,后来发现这种设计亦适合作为防空舰使用。战争中亚特兰大号护卫大黄蜂号参加了中途岛海战,战役结束后又参加了惨烈的瓜岛战役。1942年10月参加了圣克鲁斯海战,11月在瓜岛以北的海战中,亚特兰大号被日本晓号驱逐舰的鱼雷击中,13日被放弃。"]],
        "z31_R": ["female", "KMS", 3, ["dajiaoduguibi", "quzhudd", "Z", "Z_qianghua", "Zqujingying"], ["des:1936年AM型驱逐舰首舰,该级建造于战争爆发后,相比1936A型改动很少。该舰装备150毫米主炮,强于一般驱逐舰。Z-31主要参与海峡和北欧的战斗,幸存到了战后并赔偿给法国。"]],
        xuefeng_R: ["female", "IJN", 3, ["dajiaoduguibi", "quzhudd", "xiangrui", "yumian"], ["des:雪风号是日本名气最大的驱逐舰,出名的原因是她玄幻般的运气。雪风号参加了日军几乎所有恶战：包括中途岛,瓜岛战役,莱特湾海战和菊水特攻等,也曾为金刚号,大和号,信浓号等大舰护航。神奇的是不管战况多激烈,同行的军舰损失多惨重,但是雪风号却屡屡无损生还,连中破都不曾有过。战争结束后,美国抽到雪风作为赔偿,但是却转交给了民国,改名为丹阳号。三年后,丹阳随校长一起撤到了台湾。作为台湾少有的可用大舰,台湾时期的丹阳还进行了美式装备改装,一直服役到60年代。"]],
        kangfusi_R: ["female", "USN", 3, ["dajiaoduguibi", "quzhudd", "31jiezhongdui"], ["des:康弗斯属弗莱彻级驱逐舰,她也是著名的第23驱逐舰中队的一员,该中队在圣乔治角海战等一系列战斗中表现出色,指挥官阿利伯克也因此有着31节伯克的外号。康弗斯参加了后期的诸多重大战役,曾救援了遭遇神风的友军。战争胜利后整个中队被授予总统集体嘉奖,康弗斯于59年转交西班牙海军。"]],
        "47project_R": ["female", "ΒΜΦCCCP", 3, ["dajiaoduguibi", "quzhudd", "xinqidian"], ["des:　海军计划的一级大型驱逐舰,与传统驱逐舰不同的是她设计有装甲带与舰载机,由于工业不足与设计指标过高,47工程修改设计后才具备可行性,但战争爆发打断了建造。战后47工程修改了设计,并且延续到41型驱逐舰不惧号上。"]],
        guzhuyizhichuixue_R: ["female", "IJN", 3, ["dajiaoduguibi", "quzhudd", "guzhuyizhi"], ["des:吹雪型特型驱逐舰首舰,相比之前的老式驱逐舰,该型是一种新式设计,采用艏楼船型和连装主炮,特型驱逐舰也奠定了之后日本驱逐舰特征基础。吹雪号在第四舰队事件后进行了改装,以克服重心和强度问题。战争开始后在马来海域作战,42年1月海战中协同击沉了英国驱逐舰珊耐特号。1942年10月的萨沃岛海战中被美军击沉。"]],
        shuileizhanduichuixue_R: ["female", "IJN", 3, ["dajiaoduguibi", "quzhudd", "shuileizhandui",], ["des:吹雪型特型驱逐舰首舰,相比之前的老式驱逐舰,该型是一种新式设计,采用艏楼船型和连装主炮,特型驱逐舰也奠定了之后日本驱逐舰特征基础。吹雪号在第四舰队事件后进行了改装,以克服重心和强度问题。战争开始后在马来海域作战,42年1月海战中协同击沉了英国驱逐舰珊耐特号。1942年10月的萨沃岛海战中被美军击沉。"]],
        mingsike_R: ["female", "ΒΜΦCCCP", 3, ["dajiaoduguibi", "quzhudd", "manchangzhanyi"], ["des:明斯克级驱逐舰是之前列宁格勒级的完善型,除了稳定质量和设计外,基本保留了列宁格勒级的设计。明斯克号驱逐舰在战争期间主要执行对岸火力支援任务,曾经被敌机炸沉,但是在之后又浮起并修复。战争胜利后明斯克改为训练舰使用。"]],
        yinghuochong_R: ["female", "RN", 3, ["dajiaoduguibi", "quzhudd", "zhongzhuangcike", "wuweizhuangji"], ["des:G级驱逐舰之一,G级于30年代后期建造了24艘,主炮为四座单装主炮。40年她参加了挪威战役,4月8日萤火虫号与德军希佩尔海军上将号重巡洋舰遭遇,在激烈的战斗中萤火虫号释放烟雾并发射鱼雷,最终借助烟雾掩护猛烈撞击了希佩尔海军上将号,造成希佩尔海军上将号500吨进水,而萤火虫号也因为这次英勇的战斗而沉没。"]],
        "u1405_R": ["female", "KMS", 3, ["qianting", "qianxingtuxi"], ["des:由于普通潜艇水下动力受电池性能限制,德国海军考虑研发一种不依赖空气的高效水下动力系统。U-1405的动力系统采用使用过氧化氢的瓦尔特发动机,这种动力可以在水下运行,并且能让潜艇在水下达到超过20节的高速。不过发动机的缺陷是自带燃料用光后,潜艇就失去动力。U-1405是作为实战目的建造的瓦尔特潜艇,其吨位只有400吨左右。虽然是实战型号,但是她只参与了训练和实验。"]],
        baiyanjuren_R: ["female", "RN", 3, ["junfu", "hangkongzhanshuguang"], ["des:百眼巨人号航母是世界上第一级全通甲板的航空母舰。在飞机运用到海战中之后,为了加强飞机的运用能力,英国人便改装了一些军舰以搭载飞机,经过经验的积累,英国人改装了百眼巨人号航母,使用了全通的飞行甲板。百眼巨人号没有赶上一战,在二战中主要执行训练任务。"]],
        changchun_R: ["female", "PLAN", 3, ["daoqu", "sidajingang"], ["des:　苏联愤怒级驱逐舰17号舰,苏联建造的愤怒级借鉴了意大利的设计经验。前后背负式布置了4门130毫米舰炮。由于苏联对德国战争中,海战并不是主战场,因此果敢号主要执行护航任务。果敢号参加了二战并幸存下来,战后在1955年被出售给新中国海军,改名为长春号,90年退役后保存在山东乳山市。"]],

        "u47_R": ["female", "KMS", 3, ["qianting", "u47_xinbiao", "u47_huxi"], ["des:U-47号是德军的一艘王牌潜艇,属VIIB型。1939年10月她大胆穿越了斯卡帕湾的封锁线,潜入英国海军的基地内,当晚用鱼雷击沉了英国皇家橡树号战列舰。回到港口后U-47号受到了热烈的欢迎,并被授予了骑士十字勋章。在随后的战斗巡航中,U-47号总共击沉了16万吨的船只。1941年3月7日的第九次战斗巡航中U-47号失踪,至今没有其下落和定论。"]],
        "u81_R": ["female", "KMS", 3, ["qianting", "u81_langben", /* "u81_zonglie", */ "u81_xunyi"], ["des:U-81号潜艇最著名的战例发生在1941年的地中海。当时皇家方舟号航母从马耳他驶出后,遭到了U-81的雷击,尽管U-81只命中了皇家方舟号一枚鱼雷,但是处置不当导致这艘在追歼俾斯麦中立下功劳的航母最终沉没。此后的U-81在破交作战中击沉了不少商船。1944年1月,U-81遭到空袭沉没。"]],
        "z1_R": ["female", "KMS", 3, ["dajiaoduguibi", "quzhudd", "Z", "z1_Zqulingjian"], ["des:1934型舰队驱逐舰首舰。德国突破条约之后开始建造大型驱逐舰,吨位比他国驱逐舰都略大一些,装备5门单装127毫米炮。由于高温锅炉的技术问题,她动力系统稳定性不高。Z1号（莱伯勒希特·马斯号）的服役生涯很短暂,1939年执行了布雷任务,在1940年破交战中遭到己方HE111轰炸机误击沉没。"]],
        "z16_R": ["female", "KMS", 3, ["dajiaoduguibi", "quzhudd", "Z", "z16_lianhuanbaopo", "z16_shuileibuzhi"], ["des:1934A型驱逐舰11号舰,1934A是1934的改良型,改进了适航性与动力系统设计。Z16号（弗里德里希·埃科尔特号）开战之后主要执行对英国的布雷任务。在巴伦支海海战中被英国轻巡洋舰谢菲尔德号击沉。"]],
        "z18_R": ["female", "KMS", 3, ["dajiaoduguibi", "quzhudd", "Z", "z18_weisebaoxingdong"], ["des:德国1936型驱逐舰六艘都参加了挪威战役,并在战役中损失了五艘。Z18（汉斯·吕德曼）在纳尔维克海战中被击伤,之后在海岸搁浅。"]],
        "z17_R": ["female", "KMS", 3, ["dajiaoduguibi", "quzhudd", "Z", "z17_naerweikejingjie"], ["des:　德国1936型驱逐舰总体上加大了吨位,改善了舰艏设计以提高适航性。Z17（迪特尔·冯·勒德尔）号驱逐舰在纳尔维克海战中击伤了哥萨克人号,最终被英军击沉。"]],
        "z21_R": ["female", "KMS", 3, ["dajiaoduguibi", "quzhudd", "Z", "z21_tuxi"], ["des:1936型驱逐舰5号舰,1936年型是是1934型的放大改良型,表现出了不俗的性能,可以与英国部族级对攻而不落下风。Z21号（威廉·海德坎姆号）于1939年服役,1940年参与了攻击北欧行动,并占领了纳尔维克,之后英军驱逐舰突袭了港内的德国驱逐舰,旗舰Z21号遭到英军厌战号战列舰的炮击沉没。"]],
        "z22_R": ["female", "KMS", 3, ["dajiaoduguibi", "quzhudd", "Z", "z22_tuxixiawan"], ["des:1936型驱逐舰6号舰。1940年6艘1936型驱逐舰都参加了攻击北欧行动,在纳尔维克海战中,Z22号（安东·施米特号）被英国海军击沉,而这次海战中,参战的6艘1936型全部被击沉。"]],
        kewei_R: ["female", "RN", 4, ["hangmucv", "matapanjiaozhijian", "zhongbangtuxi"], ["des:      装甲航母可畏号在地中海战场有着出色的表现,在马塔潘角海战中,可畏出色的航空掩护有力支援了英国舰队的作战,她的鱼雷机击伤了维内托和意大利巡洋舰,直接助攻了厌战等主力舰的战绩。尽管在克里特战役期间可畏号遭到轰炸,但由于防护出色,可畏号并未战沉。在战争末期的太平洋战场,受到神风攻击的可畏号受损程度也明显小于美式航母,证明了自身设计的价值。可畏号在战争胜利后,于47年退役。"]],
        hude_R: ["female", "RN", 4, ["zhuangjiafh", "zhanliebb", "huangjiahaijunderongyao", "huangjiaxunyou", "tianshi"], ["zhu", "des:      英国史上最著名的战列巡洋舰。在20至30年代,胡德号长期作为英国海军的象征,频繁出访世界各地。胡德号在40年参与了针对投降后法国舰队的抛石机行动,重创了法国海军。41年的海战中,胡德号同威尔士亲王号一同拦截俾斯麦号和欧根亲王号。"]],
        gesakeren_R: ["female", "RN", 3, ["dajiaoduguibi", "quzhudd", "tiaobangzuozhan"], ["des:部族级驱逐舰的4号舰,该级驱逐舰是最著名的英国驱逐舰。哥萨克人号参加了第二次纳尔维克海战,痛击了德军驱逐舰。41年参与过围歼俾斯麦号的行动。1941年10月哥萨克人号被德军潜艇击沉。"]],
        kente_R: ["female", "RN", 3, ["huokongld", "zhongxunca", "guochuan", "baixiang"], ["des:该舰为肯特级重巡洋舰首舰,由于防护薄弱,经常被戏称为“白象”。肯特号于20年代服役,初期水线装甲带只有25.4毫米。在30年代末期,肯特号和其余重巡都进行了改装,加强了防护。肯特号在二战中参加了围捕斯佩伯爵海军上将号的战斗,1940年在地中海被击伤,回到本土修理时加装了大量雷达设备。1941年年末肯特号搭载外交官前往苏联会见总书记。肯特号平安的度过了战争,于1948年退役。"]],
        shengwang_R: ["female", "RN", 4, ["zhuangjiafh", "zhanliebb", "zuihouderongyao", "29jienaerxun"], ["des:声望级战列巡洋舰首舰。声望级追求高航速而防护不足,在30年代的改装中,声望级重点加强了装甲防护。在战争开始前进行了更彻底的改装,更新了舰桥和防空火力。战争爆发后声望号参加挪威战役,在韦斯特湾海战中声望号利用有利条件单舰击退了两艘沙恩霍斯特级。1941年参与了围歼俾斯麦号行动,后长期担任直布罗陀H舰队旗舰,并幸存到战后,也是英国三艘战巡中唯一幸存到战后的。"]],
        shenluopujun_R: ["female", "RN", 4, ["huokongld", "zhongxunca", "hongseqiangwei"], ["des:什罗普郡是伦敦级重巡洋舰四号舰。在战争早期,什罗普郡主要执行护航与武装巡逻任务。在萨沃岛海战中,原澳海军堪培拉号重巡洋舰战沉。皇家海军将什罗普郡转交澳海军顶替堪培拉号巡洋舰的战损。什罗普郡参加了太平洋战场诸多战役,在苏里高海战中与盟军一道截击了来袭战列舰。在战争胜利时,什罗普郡参加了签字仪式。"]],
        lafei_R: ["female", "USN", 4, ["dajiaoduguibi", "quzhudd", "bujushenfeng"], ["des:艾伦·萨姆纳级拉菲号驱逐舰（DD724）的舰名继承自一艘英雄军舰,前代拉菲号曾经在所罗门海战中勇敢地挑战日军的比睿号战列舰。而这一代拉菲也毫不逊色。在冲绳战役期间,她执行雷达哨舰任务时在短时间内遭到了约五十架神风飞机的攻击,被直接撞击六架,命中四弹。但是拉菲坚持战斗,舰长拒绝弃舰并率舰返回了关岛。这是战争史上的一个奇迹,而这艘坚毅的驱逐舰一直服役到了冷战时期。75年退役后成为了博物馆。"]],
        sp_lafei_R: ["female", "USN", 3, ["dajiaoduguibi", "quzhudd", "shenfeng", "buju", "qiangyun", "yuanjun"], ["des:艾伦·萨姆纳级拉菲号驱逐舰（DD724）的舰名继承自一艘英雄军舰,前代拉菲号曾经在所罗门海战中勇敢地挑战日军的比睿号战列舰。而这一代拉菲也毫不逊色。在冲绳战役期间,她执行雷达哨舰任务时在短时间内遭到了约五十架神风飞机的攻击,被直接撞击六架,命中四弹。但是拉菲坚持战斗,舰长拒绝弃舰并率舰返回了关岛。这是战争史上的一个奇迹,而这艘坚毅的驱逐舰一直服役到了冷战时期。75年退役后成为了博物馆。"]],
        salemu_R: ["female", "USN", 4, ["huokongld", "zhongxunca", "jingruizhuangbei"], ["des:萨勒姆号是德梅因级2号舰。由于完工时战争已经结束，强大的自动主炮没有发挥的机会。她服役之后主要担任舰队旗舰，并且于1959年退役，现在停泊在昆西市作为博物馆。在50年代的电影《河口之战》中，萨勒姆扮演了斯佩伯爵。"]],
        "u505_R": ["female", "KMS", 3, ["qianting", "dananbusi", "houfu"], ["des:该艇属IX-C型潜艇,于42年建成,她在德军服役生涯中一共击沉了8艘总计4万吨的盟军船只。让U-505成名的事件发生在44年6月。当时U-505被美军的反潜编队发现并击伤,鉴于形势,艇员浮出水面并弃艇。这艘潜艇之后被美军俘获并进行了抢修运回本土,上面的一些发报机和密码本被盟军获得。至今这个特别的战利品依然在美国的博物馆中对外展出,这也是唯一存世的IX-C型潜艇。"]],
        jialifuniya_R: ["female", "USN", 4, ["zhanliebb", "zhuangjiafh", "zhanliexianfuchou"], ["des:田纳西级2号舰,在20年代的年度大演习中,她表现优秀。1940年成为美军最早装备CXAM雷达的几艘军舰之一。在日军偷袭珍珠港中加利福尼亚号被重创,一直到1944年才修复完毕重返战场,修复的同时加利福尼亚号也进行了性能上的改装。苏里高海战中,加利福尼亚号同其余在珍珠港受难的姐妹一道,用战舰的方式完成了对日军的复仇。"]],
        jifu_R: ["female", "ΒΜΦCCCP", 2, ["quzhudd", "dajiaoduguibi", "jifu_R_weicheng", "jifu_R_yuanjing", "jifu_R_lingwei", "jifu_R_yuanqin", "jifu_R_yuanqin"], ["des:基辅是苏联海军大舰队计划中的一环,她的设计吸取了塔什干和列宁格勒等驱逐舰的技术,同时航速和火力也保持了非常强的水平。尽管基辅在战前已经开工,但还是因为战况的影响而停工。在战争末期,未完工的基辅被拖回船厂,并修改了设计准备继续建造,但由于相比战后的新驱逐舰设计优势不大,所以并没有最终建造完成。"]],
        "yi25_R": ["female", "IJN", 3, ["qianting", "liaowangtai"], ["des:　该舰于1939年开工,1941年10月服役,其超过3000吨的大排水量允许携带更多设备,包括一架零式小型水侦,以及一门被广为使用的14cm甲板炮。该舰自太平洋战争起便执行了多次巡航任务,如在战争初期于美国西海岸的军事行动,以及在次年9月大胆地炮击及空袭了美国本土目标。该舰在近3年的巡逻任务中屡次取得瞩目战绩,直至1943年9月在圣埃斯皮里图岛东北侧240km外的海域,被多艘美国驱逐舰围剿战沉。"]],
        shiyu_R: ["female", "IJN", 3, ["dajiaoduguibi", "quzhudd", "jishiyu_R", "jishiyu_R1"], ["des:她在海军中以幸运而著名,参加过多次激烈海战都能最终幸存下来。在激烈的苏里高海战和维拉湾海战中,她都是编队中唯一的幸存。不过到45年,她还是被一艘潜艇击中沉没。"]],
        dujiaoshou_R: ["female", "RN", 3, ["junfu", "xiuqi", "wanbei"], ["des:30年代英国设计了一级飞机修理舰,以修理航母部队载机,由于要求修复的飞机可以直接起飞,索性将她设计成了航母的结构,可当成航母使用。独角兽号于1942年完工,初期主要被当作航母使用,在地中海执行支援任务。1943年年末起,独角兽号加入太平洋战场作为航母支援舰使用,在冲绳战役期间修复了大量飞机。冷战时期独角兽号还参加了朝鲜战争,最终于50年代退役。"]],
        jiate_R: ["female", "USN", 3, ["fangqu", "mbmeibu"], ["des:基林级驱逐舰之一,由于服役太晚没有参加二战的实战。服役之后主要在大西洋活动。在1955年基阿特进行了改装,成为世界上第一艘导弹驱逐舰,其换装了双联防空导弹发射架,76毫米高炮和反潜鱼雷。在1957年为了显示其地位,刷上了DDG-1的编号。这艘划时代的军舰于1968年退役。"]],
        getelan_R: ["female", "OTHER", 3, ["mujizhengren", "pingduzhanhuo", "shixiangquanneng"], ["des:出于海防和海军航空的需求,瑞典设计建造了这一级航空巡洋舰。尽管吨位在5000吨左右,但是哥特兰的装备齐全,载机量也达到了6-8架。哥特兰也是最早的航空巡洋舰,之后的类似军舰或多或少均受其影响。哥特兰漫长的服役期中最著名的事迹是发现了俾斯麦和欧根的编队。而在这之前英海军正在满世界找她们。"]],
        rangbaer_R: ["female", "MN", 4, ["zhanliebb", "zhuangjiafh", "pangguanzhe"], ["des:让巴尔号战列舰是黎塞留级2号舰。在陆地战场失利时,黎塞留接近完工并撤退到海外,而让巴尔仅完成了一座炮塔,且具备航行能力,撤退到了达喀尔。在停泊期间,她还受到了马萨诸塞炮击和突击者的轰炸。两舰在后来都加入盟军作战,但由于让巴尔完工程度不高,并未参加战斗。在战争胜利后,考虑到战列舰巨大的象征意义,让巴尔以战列舰状态建造完工。她的电子设备和防空能力比黎塞留更强,船体也修改了设计,有更好的水下防护系统。在运河冲突中,让巴尔也曾开火支援。"]],
        dafeng_R: ["female", "IJN", 4, ["hangmucv", "chuansuohongzha", "hangkongyazhi"], ["des:　大凤号是日本设计建造的装甲航空母舰。与其它日本海军航空母舰不同的是,大凤号预备在舰队中承担起支援其他航母作战的功能,因此大凤号将船舰的防护性摆在首位,重点增强装甲。竣工后被编入第三舰队第一航空战队,担任旗舰参加了马里亚纳海战。6月19日,大凤号在飞机起飞作业时,被美国潜艇大青花鱼号发射鱼雷并命中其右舷,最终因损管不当而沉没。"]],
        dahuangfeng_R: ["female", "USN", 4, ["hangmucv", "yuanyangpoxi"], ["des:　　大黄蜂号是约克城级航母3号舰。她服役后第一项作战任务就是搭载B25轰炸机轰炸东京。在4月18日,杜立特带领的B25机群从大黄蜂号上起飞,完成了轰炸任务并在中国迫降。5月中旬,大黄蜂号在内的全部约克级航母作为主力参加了中途岛海战并击溃了日本机动部队,可以说正是她们三位扭转了太平洋的局势。在42年10月的圣克鲁斯海战中,大黄蜂号击伤了翔鹤号和筑摩号,但是自身也被重创,之后被驱逐舰击沉。"]],
        biaoqiang_R: ["female", "RN", 1, ["dajiaoduguibi", "quzhudd", "juejingfengsheng"], ["des:　标枪级驱逐舰首舰。英国于部族级之后建造的驱逐舰,其设计也成为战时应急驱逐舰的范本。二战中标枪号参加了纳尔维克海战,战斗中标枪号被德国驱逐舰击伤了船首。修复之后主要在地中海作战,并于1949年退役。"]],
        yuekecheng_R: ["female", "USN", 4, ["hangmucv", "saqijian"], ["des:　　约克城级是美国二战前期的主力航母,她的设计吸取了之前级别的经验,布局更加合理。约克城号同列克星敦号一起参加了珊瑚海海战,在海战中被击伤。因为前线急需航母应对中途岛战事,在短短72小时内她就修复完毕。中途岛战役中,三艘约克城级航母联手将日军最精锐的航母部队歼灭,但约克城号自己也被飞龙号两波攻击击伤,最后被I168号潜艇击沉。值得一提的是著名的萨奇少校当时就在约克城号上,他发明的萨奇剪战术使得美军战机可以发挥优势对付零战。"]],
        shengqiaozhi_R: ["female", "RN", 4, ["zhuangjiafh", "zhanliebb", "jupaohuoli"], ["des:针对日德兰和之前经验设计的皇家海军新式战列舰N3型。和之前战舰不同,该级战列舰在设计上有很多创新,圣乔治采用了独特的前中置主炮塔布局。优点是可以缩短主装甲带,集中更多的防护在武器系统。圣乔治的主炮也远大于之前的战列舰,达到了18英寸。由于华盛顿条约的签订,明显超出规格的N3型战列舰受到限制,圣乔治从未完工。"]],
        weiershiqinwang_R: ["female", "RN", 4, ["zhuangjiafh", "zhanliebb", "guanjianyiji"], ["des:英王乔治五世级2号舰。服役之后同胡德号一同参与了截击俾斯麦号的战斗,在战斗中被击伤撤退,不过她也击伤了俾斯麦号的油舱。修复之后威尔士亲王号搭载英国首相与美国总统进行了会晤,之后双方发表了著名的《大西洋宪章》。41年年末,威尔士亲王号编入Z舰队被派往远东对日本作战,在海战中包括反击号与威尔士亲王号在内的Z舰队被日本空袭击沉。"]],
        qiuyue_R: ["female", "IJN", 3, ["dajiaoduguibi", "quzhudd", "duikongzhiwei",], ["des:　秋月型是日本少有的以护卫和对空为任务的驱逐舰,为了区别雷击用的甲驱而被称做乙驱,主炮使用100毫米双联高炮。秋月号建成后主要伴随航母提供防空掩护,经历了马里亚纳海战,目睹了日本航母部队的失败。同年10月在恩加诺海战中被美军飞机炸沉。"]],
        luodeni_R: ["female", "RN", 4, ["zhuangjiafh", "zhanliebb", "bigseven"], ["des:　纳尔逊级2号舰,于1927年服役。罗德尼号同纳尔逊号、科罗拉多级、长门级一起被称为海军假日七巨头。二战爆发后罗德尼号参与了围歼击沉俾斯麦号的最后战斗,之后由于航速较慢,主要执行护航和支援任务。43年参与了在地中海的一系列作战,44年罗德尼号参与了支援诺曼底的行动,战后退役拆解。"]],
        weilianDbote_R: ["female", "USN", 3, ["dajiaoduguibi", "quzhudd", "saobaxing", "shaojie"], ["des:　这是一艘有着戏剧性经历的驱逐舰,在43年为总统座舰衣阿华号护航时她不慎对衣阿华号发射鱼雷,幸好衣阿华号躲避及时,没有造成更大后果。在冲绳战役中,她担任危险的雷达哨舰时被神风攻击撞中,整个船体都被抬离水面并最终沉没,但是幸运的是在过程中没有一名船员牺牲。"]],
        xianghe_R: ["female", "IJN", 4, ["hangmucv", "beihaidandang"], ["des:　翔鹤型是日本退出条约后建造的舰队航母,由于不再受条约限制,所以她的设计比之前的日本航母更加成熟。1941年8月翔鹤竣工,同一个月后完工的瑞鹤号编为第五航空战队,一起参加了12月的偷袭珍珠港。1942年两舰参加了珊瑚海海战,海战中翔鹤号被重创,因此错过了中途岛海战,在之后的战争中作为主力鏖战在南太平洋。44年6月的阿号作战中,翔鹤号被美国潜艇棘鳍号命中四发。由于损管得力,一度控制了进水,但最终油气爆炸而沉没。"]],
        ruihe_R: ["female", "IJN", 4, ["hangmucv", "xingyundeyunyuqu"], ["des:　翔鹤型航母2番舰,41年9月服役后编入第五航空战队参加了偷袭珍珠港。在珊瑚海海战中,瑞鹤号凭借雨云躲开了美军的空袭,而翔鹤号被美军命中受创。两舰因此错过了中途岛战役。后来翔鹤号和瑞鹤号编为一航战参加了圣克鲁斯海战,这也是日本最后一次航母的战术胜利。在44年6月的阿号作战中,大凤号被击沉,瑞鹤号顶替其成为旗舰。10月,恩加诺海战中,编入诱饵舰队的瑞鹤号被CV16列克星敦号（又称：蓝色幽灵）的舰载机所击沉。"]],
        yuhei_R: ["female", "IJN", 4, ["huokongld", "zhongxunca", "diwuzhandui"], ["des:她是该级重巡洋舰的三号舰。装备五座双联主炮。在该级相继完工后,她们被编为第5战队。在战前时期,本舰及其姐妹舰均经过了数次改造以提升性能。在战争爆发后,第5战队随队参与了南方作战。爪哇海战中本舰及其舰队击沉盟军德·鲁伊特等军舰。在43年的奥古斯塔皇后湾海战中曾同美国巡洋舰交手。莱特湾海战中羽黑一度受损,并且并未返回本土,受损一直没有彻底修复。在45年的一次运输任务中,遭遇索玛雷兹等英国驱逐舰,最终被维纳斯号驱逐舰击沉。"]],
        jinqu_R: ["female", "RN", 3, ["fangkong2", "qingxuncl", "bisikaiwanshoulie"], ["des:进取号是翡翠级2号舰,其舰首采用连装主炮取代了之前的单装主炮,这种连装炮设计也被后来的英国巡洋舰沿用。战争中进取号主要执行搜捕德国袭击舰的任务,43年在比斯开湾的战斗中她曾经重创德国舰艇。同翡翠号一样,进取号也参加了对诺曼底的支援任务,战争胜利后进取号于46年退役。"]],
        sp_aisaikesi_R: ["female", "USN", 4, ["hangmucv", "maliyanaliehuoji"], ["des:埃塞克斯级舰队航母设计上汲取了此前诸多级别航母的经验,使其性能达到了一个全新的高度。美国参战后,其惊人的工业机器全力开动,埃塞克斯号在42年12月服役。这一量产舰队航母开始如下饺子般陆续下水。埃塞克斯级是美国二战后期的主力航母。马里亚纳海战中埃塞克斯号在内的美国航母将日军航母部队彻底击溃,奠定了战争的走向。冲绳战役中,她参加了对大和号的围攻。东京湾,她见证了战争的胜利。在冷战中经过改造的埃塞克斯号也继续活跃,一直到69年才退役。"]],
        boerzhanuo_R: ["female", "RM", 4, ["shixiangquanneng", "tebiekongxi"], ["des:波尔扎诺号是意大利建造的第3级重巡洋舰,前者分别是高航速轻防护的塔兰托级和重防护的扎拉级。波尔扎诺保持了高航速,并一定程度加强了防护。在战争期间,虽然波尔扎诺参加了历次重大海战,但都没有出色表现,反倒两次被潜艇击伤,波尔扎诺受伤后,有过改造为航空巡洋舰的计划。但随着意大利的停战,波尔扎诺落入德方,于44年被英军击沉。"]],
        jialibodi_R: ["female", "RM", 4, ["qingxuncl", "fangkong2", "beijixingweishe"], ["des:加里波第是阿布鲁奇公爵级巡洋舰2号舰（佣兵队长5批次）该级巡洋舰有着很强的防护力。 在战争中,加里波第号作为主力巡洋舰参加了多次海战,表现不错并最终幸存到战后,在战后中继续服役。冷战期间,加里波第加装了新的电子设备和武器继续服役,并担任海军旗舰。1957年根据协议,加里波第进行了二战之后的第二次改造,装备了全新的小猎犬防空导弹与北极星发射筒。"]],
        ninghai_R: ["female", "ROCN", 3, ["fangkong2", "qingxuncl", "jianduixunlian"], ["des:　1931年中国向日本订购的一艘轻巡洋舰。该舰吸取了夕张号的设计经验,布局紧凑,火力强于一般同吨位军舰。出于训练目的,该舰虽然只有2600吨左右,但是水上飞机,鱼雷均齐备,也正因为过多的装备导致该舰适航性不佳。1937年全面抗战爆发,宁海号死守江阴防线,并战沉于此。"]],
        sp_ninghai_R: ["female", "ROCN", 3, ["fangkong2", "qingxuncl", "aizhi", "longgu", "jianghun"], ["des:　1931年中国向日本订购的一艘轻巡洋舰。该舰吸取了夕张号的设计经验,布局紧凑,火力强于一般同吨位军舰。出于训练目的,该舰虽然只有2600吨左右,但是水上飞机,鱼雷均齐备,也正因为过多的装备导致该舰适航性不佳。1937年全面抗战爆发,宁海号死守江阴防线,并战沉于此。"]],
        yiahua_R: ["female", "USN", 4, ["zhuangjiafh", "zhanliebb", "zhizhanzhige"], ["des:衣阿华级战列舰是U海军在战争期间最新式的战列舰,在火力与防护有所增强的情况下,相比前代的南达与北卡,衣阿华的航速超过30节。衣阿华于43年服役,并于同年负责运送总统参加德黑兰会议。44年衣阿华转战太平洋战场,在莱特湾海战期间,衣阿华及其姐妹舰本有与大和级交手的机会,但敌方舰队已经先行转向。在战争后期,衣阿华主要依靠其高速执行护航与火力支援任务。在冲绳战役时本舰预备拦截大和号,但大和号最终被航母空袭击沉,双方最强战列舰就此失去交手机会。"]],
        dajingbeishang_R: ["female", "IJN", 3, ["zhongleizhuangjiantuxi", "jianjianleiji"], ["des:球磨型轻巡3番舰。41年北上号被改装为了雷击巡洋舰,全舰共装备了十座四联装鱼雷发射器,单边齐射达到了二十枚鱼雷。但由于海战环境的变化,她始终没有派上用场。她在1942年拆除了八座鱼雷发射器,改为了高速运输舰。44年北上号改装为人操鱼雷“回天”母舰。北上号也是唯一残存到战后的球磨级,在1946年拆毁。"]],
        wugelini_R: ["female", "RM", 3, ["dajiaoduguibi", "quzhudd", "fenzhandaodi"], ["des:　乌戈里尼•维瓦尔迪号属航海家级驱逐舰5号舰。乌戈里尼•维瓦尔迪号也同姐妹舰安东尼奥•达诺利号一样坚持到了1943年意大利投降,在接应意大利主力舰队一同前往盟军港口时遭到了德军阻截,在规避中触雷,两姐妹舰在不到一天的时间内相继沉没。"]],
        xukufu_R: ["female", "MN", 3, ["qianting", "huofu", "xunqian"], ["des:絮库夫号是法国建造的一艘大型潜艇,她搭载了潜艇上罕见的203毫米双联主炮,同时还搭载了水上飞机,这些一般是重巡洋舰的配备。她还在甲板上装备了类似驱逐舰的回旋式的鱼雷发射器。40年法国迅速战败后,絮库夫号在盟军阵营参加作战,在42年与商船相撞的事故中沉没。"]],
        yaergushuishou_R: ["female", "RN", 3, ["fangkong2", "qingxuncl", "jinyangmaozhishi", "zhengzhansihai"], ["des:亚尔古水手号是黛朵级巡洋舰的一艘。如同她的名字一样,亚尔古水手号巡洋舰的航迹也遍布东西。在战争初期亚尔古水手号主要在大西洋战场作战。在一次出击中,亚尔古水手号遭到潜艇雷击,舰艏艉都被炸飞,瞬间舰身短了约50米。进行临时修理后,亚尔古水手号单独穿越大西洋前往后方进行修理。在修理完成后,亚尔古水手号参与了诺曼底作战与远东作战。"]],
        mist_dujiaoshou_R: ["female", "RN", 3, ["junfu", "shuqinzhiyin",], ["des:指挥官大人,您贵安。我是轻型航空母舰独角兽。为守护我们第四舰队那些美丽的花朵,也为了指挥官大人,我会尽心尽力工作。今后还望请多指教。"]],
        mist_xiawu_R: ["female", "IJN", 3, ["quzhudd", "dajiaoduguibi", "yixinyiyi"], ["des:我是属于NeoForce第一舰队,识别号码NF001的夏霧。我是个初来乍到的新人,敬请提督指教。"]],
        mist_shanhuhai_R: ["female", "USN", 4, ["hangmucv", "buxiuzhanshi"], ["des:Nice to meet you~航空母舰珊瑚海~。经历比较丰富,现在担任指导员工作。海战不用说,陆战也很在行~。啊,当然陆战的时候要卸掉舰装,拿枪战斗。"]],
        "u96_R": ["female", "KMS", 3, ["qianting", "hailangchuji"], ["des:德国U-96潜艇是一艘VIIC型中型潜艇。在战争期间U-96一共完成了11次战斗巡航,战绩为18万吨,是一艘王牌潜艇,一位德国战地记者随着潜艇出航,拍摄了大量照片,使其广为出名。不过,让U-96彻底出名的是《从海底出击》电影。电影中的主角艇,即以U-96为原型,和电影结尾不同,U-96的艇长并没有因空袭阵亡,而是幸存到战后,还参与并指导了电影拍摄。这部长约5个多小时的电影真实地反应了残酷的潜艇战,是一部载入史册的佳作。"]],
        lundun_R: ["female", "RN", 3, ["huokongld", "zhongxunca", "guochuan", "yangwangxingkong"], ["des:伦敦级巡洋舰首舰。该级是肯特级的后续级别,防护薄弱的缺陷也被继承。伦敦号在1939年左右进行了一次彻底的改装。使得伦敦号外观同其余重巡姐妹差别很大,外形更接近爱丁堡级轻巡洋舰。二战中的伦敦号主要执行拦截德军和护航任务。让伦敦号出名的事情并不在二战而是发生在中国：在1949年4月的长江紫石英号事件中,试图支援紫石英号的伦敦号被解放军火炮痛击,三座主炮塔被击毁,舰长重伤,只得撤退。"]],
        aisijimoren_R: ["female", "RN", 3, ["dajiaoduguibi", "quzhudd", "zhengzhansifang", "binghaihuhang"], ["des:部族级驱逐舰的5号舰,该级以世界各个民族命名。爱斯基摩人号参加了纳尔维克海战,在海战中被德军驱逐舰打掉了舰首。修复之后主要执行护航任务,并在战斗中击沉过德军潜艇,也曾进行过一次接舷跳帮作战。战后于1949年退役。"]],
        sp_zhongtudao_R: ["female", "USN", '3/4', ["hangmucv", "zhuangjiajiaban", "xiandaihuagaizao"], ["des:中途岛级航母是美国海军在二战中设计的最后一型航母,也是海军第一艘真正意义上摆脱了条约限制的航母（前代埃塞克斯级由于设计时间过短而继承了很多约克城级的特征）,在核心思路上大量参考了英国的装甲航母设计,而在舰体设计上则借用了蒙大拿级的设计。中途岛号在1945年3月下水时的排水量为45000吨,是此后10年内全球最大的现役航母；在长达52年的服役史中,她是海军首艘接触斜角甲板概念的航母,先后参与了越南战争（击落了战争中第一架和最后一架敌机）和海湾战争,接受了两次大规模现代化改造,最终于1997年退役,作为博物馆保存至今。"]],
        guying_R: ["female", "IJN", 4, ["huokongld", "zhongxunca", "zhanxianyuanhu"], ["des:该型是日本在八八舰队时期设计的侦查巡洋舰,由于之后海军条约的签署,根据规定古鹰型被划为重巡洋舰。在37年,两艘古鹰型进行了大改装,单装主炮换为新式连装炮,其余武备和设施也进行了更新,外形上和青叶型很相似。古鹰号在战争初期很活跃,参与了威克岛到中途岛的一系列作战。42年古鹰号编入三川的第八舰队,在萨沃岛海战中重创了美军。不过在同年10月的海战中,古鹰号好运不再,被美军击沉。"]],

        pachina_R: ["female", "RM", 4, ["yaosai", "pachina_R_xinao"], ["des:位于意大利西西里的帕基罗角（Pachino）。实际上意大利的海军并未在这里修建要塞,反而是英军的次要登陆场,英军在该地登陆后还建立了临时机场。"]],
        loki_R: ["female", "KMS", 4, ["hangmucv", "loki_R_xiance"], ["des:深海版的装甲航空母舰彼得·施特拉塞尔。"]],
        southdakota_R: ["female", "USN", 4, ["zhanliebb", "zhuangjiafh", "southdakota_R_gumei", "southdakota_R_jianmiemoshi", "southdakota_R_zhaopin"], ["des:原型为美国海军南达科他级战列舰南达科他（BB-57）。"]],
        lingbo_R: ["female", "IJN", 3, ["quzhudd", "dajiaoduguibi", "zhanxian", "guishen"], ["des:吹雪型11号舰,特II型1号舰。相比特I型,绫波号增加了主炮高射功能,35年针对第四舰队事件进行了改装,战争初期隶属南方部队。1942年8月被派到瓜岛,并参加了11月的第三次所罗门海战,战斗中绫波号表现突出,至少击伤四艘美军战舰,其中包括南达科他号战列舰,绫波号自身也在此次海战中沉没。"]],
        sukhbaatar_R: ["female", "OTHER", 3, ["junfu", "sukhbaatar_R_rumeng", "sukhbaatar_R_sudaren"], ["des:CLASSIFIED*。"]],
        odin_R: ["female", "OTHER", 3, ["junfu", "odin_R_ganggenier"], ["des:CLASSIFIED*。"]],
        vestal_R: ["female", "USN", 3, ["junfu", "vestal_R_mowang"], ["des:CLASSIFIED*。"]],
        nvzaoshen_R: ["female", "USN", 3, ["junfu", "dajiaoduguibi", "xiwangdeshuguang", "qiangxiu"], ["des:女灶神号（舷号AR-4）是一艘在1913年至1946年期间服役于美国海军的修理船。在改装为修理船之前,女灶神是一条运煤船（从1909年开始）。女灶神号参与了全部两次世界大战,在日本空袭珍珠港期间,该舰在港口内遭到重创。打满整场第二次世界大战的女灶神共获得了两枚战斗之星。"]],
        bismarck_R: ["female", "KMS", 4, ["zhuangjiafh", "bismarck_R_chajin", "bismarck_R_fanji"], ["des:表里不一的“野猫”虽然一直说着带攻击性的话,但意外是个很单纯的人。长期相处,应该就能听懂她真正的意思。"]],
        tirpitz_R: ["female", "KMS", 4, ["zhuangjiafh", "tirpitz_R_jinshu", "tirpitz_R_chuanyue", "tirpitz_R_nvwangfugui"], ["des:无表情的“人偶”总是盯着手里的东西,对其他的事情缺乏兴趣。但却喜欢为他人解说姐姐说的话,这一点上,很有趣。"]],
        akagikaga_R: ["female", "IJN", 4, ["hangmucv", "shuangzi", "akagikaga_R_zongyu"], ["des:对某些人类非常执着。每次回来,都是遍体鳞伤。而且,一直躺着会对素体产生影响。"]],
        savoy_R: ["female", "RM", "2/4/1", ["yaosai", "savoy_R_xiuzhu", "savoy_R_wangong"], ["des:自称“吸血鬼”,坚称自己是人类幻想文学中的一员。在月圆之夜喜欢看着月亮发呆。一直随身带着石榴汁……？"]],
        cassone_R: ["female", "RM", 4, ["zhuangjiafh", "cassone_R_yibing", "cassone_R_weizhuangqixi"], ["des:深海版战列巡洋舰卡萨诺方案。"]],
        Xfliegerkorps_R: ["female", "KMS", 4, ["yaosai", "Xfliegerkorps_R_piaobodeying"], ["des:漂泊的“鹰”,戴着奇怪的帽子,不喜欢与其他人交流。但,实力很强。"]],
        "401_R": ["female", "IJN", 4, ["junfu", "shujuzaisheng"], ["des:401的诞生是由于获得yamato_R智能模块的一半。后为了拯救暴走的芙蕾雅Cyou-yamato_R而把自己的智能模块捐献出来,捐献模块后消失。不过因为S113在之前留下了yamato_R的数据备份而复活。"]],
        chaoyamato_R: ["female", "IJN", 4, ["zhuangjiafh", "zhanliebb", "yapogan"], ["des:日本战列舰A150。"]],
        jiagu_R: ["female", "IJN", 4, ["zhongxunca", "xietongzuozhan"], ["des:　加古属古鹰型2番舰,于26年完工。同古鹰号一样,在37年也进行了全面的改装以提升性能。战争爆发时加古号和古鹰号编入相通的部队作战。42年,一同编入三川的第八舰队,在萨沃岛海战中,夜战熟练的日军重创了美军,不过在归途中,加古号被美军潜艇击沉。"]],
        yamato_R: ["female", "IJN", 4, ["zhuangjiafh", "zhanliebb", "yamato_R_tongchou", "yamato_R_dikai", "yamato_R_nizhuanfanji"], ["des:深海化的大和级战列舰。她以自毁般的同仇反噬敌我,于濒死边缘掀起最后的逆转反击。"]],
        kelaosaiweici_R: ["female", "KMS", 4, ["zhuangjiafh", "zhanliebb", "kelaosaiweici_R_jinji", "kelaosaiweici_R_lunzhan"], ["des:以普鲁士军事理论家克劳塞维茨命名的德国战列舰方案。她强调持续压迫与战场调度,既能在炮战中不断寻找突破口,也能在战局开始前通过推演争夺主动。"]],
        gaobo_R: ["female", "IJN", 3, ["jing_shu", "ling_mu", "dajiaoduguibi", "quzhudd"], ["des: 本舰属于甲型驱逐舰，在同级中排行第六。本级舰基于前代小改而来，主要改动包括防空性能强化与舰桥造型优化，并使用了能将主炮抬升到75度的全新炮塔以追求高平两用能力（然而受限于主炮较低的射速与旋转速度，以及对空火控的缺失，单纯增加主炮仰角并未能使防空性能得到多少强化）。本舰于1942年8月竣工后编入第31驱逐舰队服役，参与了炮击瓜岛与圣克鲁兹群岛海战；1942年11月，在塔萨法隆格海战中，本舰作为舰队的先锋在受到敌军集火时顽强还击，为舰队的反击创造了有利条件，但自身最终被敌军集火击沉。"]],
        buzhihuo_R: ["female", "IJN", 3, ["dajiaoduguibi", "quzhudd", "yuleizhantujin"], ["des:阳炎型驱逐舰二号舰。她与姊妹舰同属日本海军主力雷击驱逐舰，在南方和所罗门方面多次投入夜战与护航任务。1944年，不知火号在菲律宾方面作战中因机动受限，最终于奥尔莫克湾附近遭美军围攻沉没。"]],
        chuannei_R: ["female", "IJN", 3, ["fangkong2", "qingxuncl", "zhanduiqijian"], ["des:川内级是5500吨轻巡的最后一批。这种轻巡被用于水雷战队旗舰。为了节约石油燃料，川内混装了一些燃煤锅炉，烟囱数量也因此达到了四个。在瓜岛战役期间，川内是田中的旗舰，田中赖三是东京快车行动（利用高速军舰向瓜岛补给）的指挥官。尽管在不利的环境下取得了一些战果，但是对局势帮助不大。川内号于43年在奥古斯塔皇后湾海战中被美军击沉。"]],
        chuxue_R: ["female", "IJN", 3, ["dajiaoduguibi", "quzhudd", "lingjupaoji"], ["des:吹雪型驱逐舰3号舰。35年在第四舰队事件中舰首断裂，这次事件暴露了日本军舰重心和强度上的问题，此后日本对有问题的军舰进行了加强。1941年编入第11驱逐舰队参与了南洋作战。42年投入到了瓜岛，参加了萨沃岛海战。1943年加入第八舰队，在库拉湾海战中受创。7月17日在布因被美军空袭击沉。"]],
        dian_R: ["female", "IJN", 3, ["dajiaoduguibi", "quzhudd", "wuyizhuangji"], ["des:日本海军驱逐舰“电”号。她擅长高速逼近与近距离突进，一旦战局失控，往往会以近乎本能的撞击撕开敌阵。"]],
        fubo_R: ["female", "IJN", 3, ["dajiaoduguibi", "quzhudd", "shuileihun"], ["des:特II型驱逐舰2号舰。特型驱逐舰虽然有着较强的水面作战能力，但是缺乏对空和反潜能力。35年敷波号进行了增加强度的改装，42年随队参加了中途岛海战。此后特型驱逐舰大多都投入到了瓜岛前线，敷波号也不例外。在瓜岛战役结束后她主要执行护航任务，于1944年9月战沉。"]],
        lei_R: ["female", "IJN", 3, ["dajiaoduguibi", "quzhudd", "shuileihun"], ["des:晓型驱逐舰3番舰，初期主要在南太平洋作战。1942年5月被调到北方舰队在阿留申作战。1942年夏投入到瓜岛前线，在第三次所罗门海战中受创。1943年参与了阿图岛作战，在行动中发生了碰撞事故。1944年在执行护航任务时被美军潜艇击沉。"]],
        shenxue_R: ["female", "IJN", 3, ["dajiaoduguibi", "quzhudd", "shuileiqiangxi"], ["des:吹雪型驱逐舰4号舰。深雪号是唯一一艘没有参加战争的特型驱逐舰：深雪号在1934年6月29日在一次同电号驱逐舰的冲撞中沉没，是该级24舰中唯一一艘非战斗损失的。"]],
        wushiling_R: ["female", "IJN", 3, ["fangkong2", "qingxuncl", "kongqianyiti"], ["des:长良型轻巡2番舰。设计上属于5500吨级水雷战队旗舰轻巡，二战爆发后五十铃号参加了南方作战和瓜岛战役。44年被美军潜艇重创后，五十铃号在修复中装上了三座89式127毫米高炮和大量机炮，成为了防空巡洋舰。莱特湾海战中编入小泽编队，在护航中表现出色。1945年4月五十铃号被美军潜艇击沉。"]],
        xiang_R: ["female", "IJN", 3, ["dajiaoduguibi", "quzhudd", "xiang_busizhishouhu"], ["des:晓型驱逐舰2番舰，建成后编入第六驱逐舰队，战争初期主要在南太平洋活动。1942年在基斯卡作战中被美军空袭击伤，7月参与了基斯卡撤退作战。1944年在商船护航中受创，修理中错过了莱特湾海战。1945年，在参与大和的特攻作战之前触雷修理。响号有着不死鸟的称号，不过她主要是靠运气避开了恶战。在战后响号被赔偿给苏联，命名为信赖号（Верный）一直使用到1963年。"]],
        tianlonglongtian_R: ["female", "IJN", 3, ["fangkong2", "qingxuncl", "yuanzhenghuhang", "yuanzhenghuwei"], ["des:天龙型轻巡洋舰一号舰“天龙”与二号舰“龙田”。两舰长期承担护航、运输与前线掩护任务，擅长把手中的资源提前分派给友军，并在回收补给后为其预置下一轮的攻防节奏。"],],
        xiangqu_R: ["female", "IJN", 3, ["fangkong2", "qingxuncl", "duomianxunlianjian"], ["des:由于之前担任训练任务的装甲巡洋舰老化，日本海军特意开发了香取型训练巡洋舰。香取型的居住性和航洋性都好于一般的轻巡洋舰，由于外事访问需要，内部装饰也更为豪华。同时出于教学目的，武器类型也相当齐全，从高炮到鱼雷均有。香取号在战争期间主要担任护卫部队的旗舰，44年香取在特鲁克以北被美军击沉。"]],
        baixue_R: ["female", "IJN", 3, ["dajiaoduguibi", "quzhudd", "baixue_jiban"], ["des:吹雪型驱逐舰2号舰，于1928年服役。战争开始后编入第11驱逐舰队活动，和吹雪号一同参与了1942年1月击沉英国驱逐舰的海战。3月参与巽他海峡作战，期间协同击沉了盟军两艘巡洋舰。1942年白雪号投入到了瓜岛前线，并参与了第二次瓜岛海战。43年白雪号在美军空袭中沉没。"]],
        xiao_R: ["female", "IJN", 3, ["dajiaoduguibi", "quzhudd", "qiangxingzhencha"], ["des:特III型驱逐舰首舰，也被划分为晓型。相比吹雪型减少了一座锅炉，外观上一号烟囱较细。竣工后，四艘晓型驱逐舰编成第六驱逐舰队一同活动。1942年参与了菲律宾海域的战斗，之后主要作为航母的护卫舰只。1942年参与了瓜岛战役，在第三次所罗门海战中被美军击沉。"]],
        yangyan_R: ["female", "IJN", 3, ["dajiaoduguibi", "quzhudd", "jiquleiji"], ["des:阳炎型是日本经过数型舰船设计的摸索之后建造的强力舰队驱逐舰，有着很强的雷击能力，但是后来不能适应立体化的海战环境。阳炎号作为护卫军舰参加了中途岛海战，之后活跃在瓜岛水域。43年5月阳炎号在战斗中触雷后丧失动力，被美军飞机击沉。"]],

        talin_R: ["female", "ΒΜΦCCCP", 4, ["qingxuncl", "fangkong2", "mijian"], ["des:塔林，苏联轻巡洋舰"]],
        botelan_R: ["female", "USN", 4, ["zhongxunca", "huokongld", "shanzhan"], ["des:波特兰，美国重巡洋舰"]],
        sp_shenxue_R: ["female", "IJN", 3, ["quzhudd", "dajiaoduguibi", "huixi"], ["des:SP深雪，日本驱逐舰"]],
        deyizhiA59_R: ["female", "KMS", 3, ["qingxuncl", "fangkong2", "duoneng", "daike"], ["des:德意志A59，德国轻巡洋舰"]],
        sp_dadian_R: ["female", "IJN", 3, ["qingxuncl", "fangkong2", "modaiqijian", "haitiantongxun"], ["des:SP大淀，日本轻巡洋舰旗舰"]],
        jiahe_R: ["female", "IJN", 4, ["hangmucv", "jidongjiandui", "jiangongchuji"], ["des:加贺，日本舰队航空母舰"]],
        tierbizi_R: ["female", "KMS", 4, ["zhuangjiafh", "qianzhi", "beizhai"], ["des:提尔比茨，德国战列舰"]],
        alasijia_R: ["female", "USN", 3 / 4, ["zhuangjiafh", "xianfeng", "kuanhuankaimu"], ["des:阿拉斯加，美国大型巡洋舰"]],
        qibolin_R: ["female", "KMS", 4, ["hangmucv", "xiaoxiao", "yingfan"], ["des:齐柏林伯爵，德国航空母舰"]],
        chuchun_R: ["female", "IJN", 3, ["quzhudd", "dajiaoduguibi", "butaihegedehuwei", "nituochuanlaila"], ["des:初春，日本驱逐舰，末期的护卫"]],


        //新武将写在这行上面
        skilltest: ["male", "OTHER", 9, ["guanxing", "jujianmengxiang", "huodezhuangbei", "huodeyanshi", "paoxiao", "guankanpaidui"], ["forbidai", "des:测试用"]],
    },
    skill: {
        ...globalskills,
        ...shiptypeskills,
        ...standard,
        ...cangqinghuanying,
        ...unfulfilledambition,
        ...historybattles,
        ...fallendemon,
        ...others,
        ...shuileizhandui,
        //这下面的大括号是整个skill数组的末尾,有且只有一个大括号。
    },
    translate: {
        //武将名翻译
        skilltest: "测试武将",
        liekexingdun_R: "列克星敦",
        qixichicheng_R: "奇袭赤城",
        wufenzhongchicheng_R: "五分钟赤城",
        qiye_R: "企业",
        bisimai_R: "俾斯麦", misuli_R: "密苏里",
        changmen_R: "长门", weineituo_R: "维内托",
        lisailiu_R: "黎塞留",
        kunxi_R: "昆西", ougengqi_R: "欧根",
        qingye_R: "青叶", beianpudun_R: "北安普顿",
        jiujinshan_R: "旧金山",
        tianlangxing_R: "天狼星", yixian_R: "逸仙",
        //degelasi: "德格拉斯", 
        yatelanda_R: "亚特兰大",
        dadianrendian_R: "大淀仁淀",
        kangfusi_R: "康弗斯", "z31_R": "z31",
        "47project_R": "47工程", xuefeng_R: "雪风",
        shuileizhanduichuixue_R: "水雷战队吹雪",
        guzhuyizhichuixue_R: "孤注一掷吹雪",
        mingsike_R: "明斯克",
        baiyanjuren_R: "百眼巨人",
        "u1405_R": "u1405",
        changchun_R: "长春",
        "1913_R": "1913战巡",
        yinghuochong_R: "萤火虫",
        jifu_R: "基辅",
        "u47_R": "u47",
        "u81_R": "u81",
        "z1_R": "z1",
        "z16_R": "z16",
        "z18_R": "z18",
        "z17_R": "z17",
        "z21_R": "z21",
        "z22_R": "z22",
        kewei_R: "可畏",
        hude_R: "胡德",
        shiyu_R: "时雨",
        dujiaoshou_R: "独角兽",
        gesakeren_R: "哥萨克人",
        kente_R: "肯特",
        shengwang_R: "声望",
        shenluopujun_R: "什罗普郡",
        lafei_R: "拉菲",
        sp_lafei_R: "SP拉菲",
        "yi25_R": "伊25",
        jiate_R: "基阿特",
        salemu_R: "萨勒姆",
        "u505_R": "u505",
        jialifuniya_R: "加利福尼亚",
        getelan_R: "哥特兰",
        rangbaer_R: "让巴尔",
        dafeng_R: "大凤",
        dahuangfeng_R: "大黄蜂",
        biaoqiang_R: "标枪",
        yuekecheng_R: "约克城",
        shengqiaozhi_R: "圣乔治",
        weiershiqinwang_R: "威尔士亲王",
        qiuyue_R: "秋月",
        luodeni_R: "罗德尼",
        weilianDbote_R: "威廉D波特",
        xianghe_R: "翔鹤",
        ruihe_R: "瑞鹤",
        yuhei_R: "羽黑",
        jinqu_R: "进取",
        sp_aisaikesi_R: "sp埃塞克斯",
        boerzhanuo_R: "波尔扎诺",
        jialibodi_R: "加里波第",
        ninghai_R: "宁海",
        sp_ninghai_R: "SP宁海",
        yiahua_R: "衣阿华",
        dajingbeishang_R: "大井北上",
        wugelini_R: "乌戈里尼",
        xukufu_R: "絮库夫",
        yaergushuishou_R: "亚尔古水手",
        mist_dujiaoshou_R: "MIST独角兽",
        mist_xiawu_R: "MIST夏雾",
        mist_shanhuhai_R: "MIST珊瑚海",
        "u96_R": "u96",
        lundun_R: "伦敦",
        aisijimoren_R: "爱斯基摩人",
        sp_zhongtudao_R: "SP中途岛",
        guying_R: "古鹰",
        lingbo_R: "绫波",

        pachina_R: "痴要塞姬",
        loki_R: "痴洛基",
        southdakota_R: "痴南达科他",
        sukhbaatar_R: "慢苏赫巴托尔",
        odin_R: "慢奥丁",
        vestal_R: "慢女灶神",
        nvzaoshen_R: "女灶神",
        bismarck_R: "贪俾斯麦",
        tirpitz_R: "贪提尔比兹",
        akagikaga_R: "贪赤城加贺",
        savoy_R: "疑萨沃尼亚",
        cassone_R: "疑卡萨诺方案",
        Xfliegerkorps_R: "疑第十航空军团",
        "401_R": "嗔401",
        chaoyamato_R: "嗔超大和",
        jiagu_R: "加古",
        yamato_R: "嗔大和",
        kelaosaiweici_R: "克劳塞维茨",

        gaobo_R: "高波",
        buzhihuo_R: "不知火",
        chuannei_R: "川内",
        chuxue_R: "初雪",
        dian_R: "电",
        lei_R: "雷",
        fubo_R: "敷波",
        shenxue_R: "深雪",
        wushiling_R: "五十铃",
        xiang_R: "响",
        xiangqu_R: "香取",
        "tianlonglongtian_R": "天龙龙田",
        baixue_R: "白雪",
        xiao_R: "晓",
        yangyan_R: "阳炎",

        talin_R: "塔林",
        botelan_R: "波特兰",
        sp_shenxue_R: "SP深雪",
        deyizhiA59_R: "德意志A59",
        sp_dadian_R: "SP大淀",
        jiahe_R: "加贺",
        tierbizi_R: "提尔比茨",
        alasijia_R: "阿拉斯加",
        qibolin_R: "齐柏林伯爵",
        chuchun_R: "初春",

        //舰种技能与全局技能翻译
        quzhudd: "驱逐", "quzhudd_info": "",
        qingxuncl: "轻巡", "qingxuncl_info": "",
        zhongxunca: "重巡", "zhongxunca_info": "",
        zhanliebb: "战列", "zhanliebb_info": "",
        daoqu: "导驱", "daoqu_info": "（可强化）你的攻击范围增加2+2X(x为技能强化次数),出牌阶段限一次,你可以弃置一张武器/装备牌,对目标使用一张不可响应的远程导弹。",
        fangqu: "防驱",
        daodan: "防空导弹",
        zhandouji: "战斗机",
        yaosai: "要塞", "yaosai_info": "(可强化)每局游戏限0/1/2次,出牌阶段,你可以增加一点体力上限,回复一点体力。",
        "fangqu_info": "（可强化）游戏开始时/出牌阶段开始时,将至多1/2/3张手牌放到武将牌上.称为防空导弹。锦囊牌被使用时,你可以移去一枚防空导弹,令其无效。",
        "fangqu_wuxie": "发射防空导弹",

        hangmucv: "航母", "hangmucv_info": "(可强化)你的出牌阶段开始时,<br>你可以将任意张：零级强化,黑桃或梅花手牌；一级强化,黑桃或梅花或红桃手牌；二级强化,任意手牌。当作万箭齐发对等量个目标使用",
        qianting_xiji: "袭击", "qianting_xiji_info": "每回合限两次,将♦/♥牌当做顺手牵羊,♣/♠牌当做兵粮寸断使用<br>你使用的锦囊牌可以对距离你2以内的角色使用。",
        qianting: "潜艇", "qianting_info": "（可强化）准备阶段或弃牌阶段开始时,若你本回合未造成伤害,你可以弃置一张红桃或黑桃/红桃或黑桃或方片/牌,视为对一个目标使用一张无距离限制的雷杀。",
        qianting_jiezi: "截辎", "qianting_jiezi_info": "其他角色跳过阶段时,你摸一张牌",
        "_yuanhang": "远航", "_yuanhang_info": "若你已受伤,你的手牌上限+1。挑战模式不屈时手牌上限+1。<br>当你失去手牌后,且手牌数<手牌上限的一半时,你摸一张牌。使用次数上限0/1/2次,处于自己的回合时+1,每回合回复一次使用次数。<br>当你进入濒死状态时,你摸一张牌,体力上限大于二时需减少一点体力上限,额外摸一张牌；死亡后,你可以按自己的身份,令一名角色摸-/2/1/1（主/忠/反/内）张牌。",
        kaishimopai: "开始摸牌", "kaishimopai_info": "判定阶段你可以减少一次摸牌阶段的摸牌,然后在回合结束时摸一张牌。",
        "_jianzaochuan": "建造", "_jianzaochuan_info": "每局游戏限一次,当你进行了至少一次强化后<br>1.出牌阶段<br>你可以弃置3张不同花色的牌,提升一点血量上限与强化上限。",//<br>2.当你濒死时,<br>你可以弃置4张不同花色的牌,回复一点体力。<br>（未开启强化,则无需强化即可使用建造。未开启建造,则强化上限仅为1级。）",
        "_qianghuazhuang": "强化装备",
        "_qianghuazhuang_info": "每回合限一次,你可以弃置二至四张牌或消耗经验,选择一至两个永久效果升级。<br>（摸牌、技能、攻击范围、防御距离、手牌上限）<br>一级强化消耗两点经验,二级强化消耗三点经验",//装备牌代表两张牌
        diewulimitai: "递杀", "diewulimitai_info": "给实际距离为1的队友递一张杀或装备牌,可以立即使用（杀只能用一次）,一回合限2次。可强化",
        "_wulidebuff": "属性伤害效果",
        "_wulidebuff_info": "火杀：令目标回合结束后,受到一点火焰伤害,摸两张牌。</br>冰杀：护甲加1伤；减少对手1点防御距离。</br>雷杀：自动判断是否流失对手体力；减少对手1点手牌上限；。</br>此角色回合结束后移除所有的进水、减速、燃烧。",
        "_hanbing_gai": "寒冰-改",
        "_hanbing_gai_info": "1.开启“属性伤害效果”的情况下,你对拥有护甲的目标造成雷属性伤害前,+1伤害值。<br>2.在你造成伤害前,若你拥有寒冰剑_技能/造成的伤害为冰属性,你可以防止此伤害并弃置目标2*X张牌,x为伤害值。与伤害效果技能配合时",
        _yidong: "移动座位", "_yidong_info": "",
        tiaozhanzhuangbei: "挑战装备",
        "tiaozhanzhuangbei_info": "挑战锁定技,游戏开始时,你将一张【回避】【此舰种的武器】和一张【望远镜】置入你的装备区。你装备区内的武器牌和宝物牌不能被其他角色弃置。",
        danzong: "增强杀",
        "danzong_info": "你使用杀后,有概率可以在造成无属性伤害附加属性：<br>潜艇、驱逐：获得雷属性的效果,<br>战列、航母：获得雷属性与改进型冰杀的效果。<br>其他舰种时：获得火属性,点燃目标。<br>效果持续到伤害结算完成时（打不穿藤甲的高爆弹与暴击藤甲的决斗）",
        /* "paohuozhunbei9_skill": "炮火准备1", "paohuozhunbei9_skill_info": "装备技能", */
        dajiaoduguibi: "规避",
        "dajiaoduguibi_info": "（可强化）若你没有装备防具,你需要使用或打出闪时可以进行一次判定,判定结果为：零级强化,方块/一级强化,桃、闪或方块/二级强化,红桃或方块,视为你使用或打出了闪。",
        "rendeonly2": "仁德界改",
        "rendeonly2_info": "给实际距离为2的队友最多两张牌,一回合限2次,给出第二张牌时,你视为使用一张基本牌。可强化",
        zhiyangai: "直言",
        "zhiyangai_info": "令一名目标角色摸一张牌并展示之。<br>若为装备牌,则其可以选择是否装备。<br>可强化(每强化一次技能,便+1技能的目标数)",
        "fangkong2": "防空",
        "fangkong2_info": "当一名角色使用的锦囊牌指定了至少两名角色为目标时,<br>你可弃置两张牌令此牌对距离你为1/3/5的任意名角色无效,可强化",
        huokongld: "火控雷达",
        "huokongld_info": "（可强化）当你使用的【杀】被目标角色使用的【闪】抵消时,你可以弃置：零级,一张杀/一级,一张黑色牌/二级,一张牌,令此【杀】依然对其造成伤害。",
        "ganglie_gai": "刚烈弱化",
        "ganglie_gai_info": "每当你受到1点伤害后,若你的体力不大于2,你可以弃置x张牌并进行判定。<br>若结果不为红桃,则伤害来源选择执行一项：1.弃置x+1张手牌,2.选择交给你一张牌;3.失去一点体力(无视护甲)。<br>若你先弃置了两张牌,则判定失败时随机获得目标的一张牌;判定成功后,目标不选择弃牌时会额外失去一张牌。可强化",
        "zhongpaoduijue": "对决",
        "zhongpaoduijue_info": "当你无法使用杀时,你可以指定一个目标,弃置最多（2/3/4）张相同花色的牌,并与目标摸等量的牌,<br>然后你与目标轮流视为对对方使用一张决斗,<br>直到双方的决斗次数超过2n,n为你弃置的牌数。强化以-1对方摸的牌",
        "zhuangjiafh": "装甲防护",
        "zhuangjiafh_info": "（可强化）每回合限一次,当你受到：零级强化,普通杀的伤害/一级强化,杀的伤害和火属性的伤害/二级强化,杀的伤害和任意属性伤害时,若你没有用护甲承受过此次伤害,你可以获得1点护甲。",
        "misscoversha": "回出杀数", "misscoversha_info": "杀被回避会回复当回合出杀次数",
        "xianjinld": "先进雷达",
        "xianjinld_info": "可以选择一个增益：1.攻击,实际距离此角色为1的队友：武器攻击距离+1;但防御杀的距离-1,队友的摸牌阶段多摸一张牌。或：2.防御距离+1,但是攻击距离-1,自己的摸牌阶段少抽一张牌。",
        //"kanpolimitai": "制空权",
        //"kanpolimitai_info": "每轮限一次,你可以将一张黑色手牌当无懈可击使用。可强化",
        kaifa: "开发装备",
        "kaifa_info": "出牌阶段,你可以展示一张未强化过的【诸葛连弩】或标准包/军争包/SP包中的防具牌,然后对其进行强化。当你处于濒死状态时,你可以重铸一张防具牌,然后将体力回复至1点。",
        huijiahuihe: "额外回合",
        "huijiahuihe_info": "当你有护甲时,你可以移除所有护甲并进行一个额外的回合；额外回合的摸牌数等于护甲数。此回合结束时,若你没有造成伤害,你摸一张牌。",
        junfu: "军辅船",
        "junfu_info": "（可强化）出牌阶段结束时,你可以把至多1/2/3张手牌存于武将牌上,如手牌般使用。<br>其他角色回合开始时,你可以把存储的牌交给ta,然后你摸一张牌。",

        //个体技能翻译
        manchangzhanyi: "漫长战役", "manchangzhanyi_info": "每轮限一次,你受到锦囊牌的伤害时,你免疫此伤害。你攻击范围内的其他角色的准备阶段,你可以弃置其一张手牌。",
        manchangzhanyi_mianyi: "漫长战役", "manchangzhanyi_mianyi_info": "",
        guzhuyizhi: "孤注一掷", "guzhuyizhi_info": "准备阶段,你可以弃置所有手牌,然后摸弃置的手牌数+2张牌,如此做,你的其他技能失效直到你的下回合开始,你计算与其他角色的距离-1,杀使用次数+1,你的手牌上限等于本回合造成的伤害。",
        guzhuyizhi2: "孤注一掷", "guzhuyizhi2_info": "",
        shuileizhandui_skill_1: "水雷战队", "shuileizhandui_skill_1_info": "",
        shuileizhandui_skill: "水雷战队", "shuileizhandui_skill_info": "你可以交给一名角色任意张牌。若你是本回合第一次发动本技能,你可以从牌堆和弃牌堆获得一张雷杀。你没有手牌时,不能成为杀的目标。",
        dumuchenglin: "独木成林", "dumuchenglin_info": "你获得【规避】。当场上没有其他航母时,杀使用次数+1。",//,你于你的回合对其他角色造成的第一次伤害时此伤害+1。",
        dumuchenglin_2: "独木成林2", "dumuchenglin_2_info": "杀使用次数+1",
        bigE: "大E", bigE_info: "你使用的第一张杀需要两张闪响应。受到你使用杀造成的伤害的角色进水（手牌上限-1直到其回合结束）。",
        xiangrui: "祥瑞", "xiangrui_info": "每名玩家的回合限一次,当你受到伤害前,你可以进行判定,判定结果为黑桃,免疫此次伤害,然后获得[祥瑞]标记。",
        yumian: "御免", "yumian_info": "锁定技,结束阶段,你移除所有[祥瑞]标记。你可以选择距你1以内的目标,让其失去一点体力并摸两张牌。若你失去了一个或以上的祥瑞标记,你可以选择的目标不受距离限制",
        hangkongzhanshuxianqu: "航空战术先驱", "hangkongzhanshuxianqu_info": "你使用转化的锦囊牌结算后,你可以展示牌堆顶的x张牌,获取其中花色各不相同的牌(x为你指定的目标数,至多为4)",
        gaosusheji: "高速射击", "gaosusheji_info": "转换技,出牌阶段你使用的第一张牌为：阳：基本牌时；阴：普通锦囊牌时。你可以令此牌额外结算一次。",
        qixi_cv: "奇袭", "qixi_cv_info": "限定技,出牌阶段,你可以令所有其他角色依次选择一项:1你弃置其区域内的两张牌,2本回合不能使用或打出手牌,3翻面。然后你可以视为使用【近距支援】。",
        rand: "随机数", "rand_info": "遇事不决？扔一个骰子吧。该技能可以生成1~6的随机数",
        duikongfangyu: "对空防御", "duikongfangyu_info": "锁定技,你发动防空时技能等级视为满级。你发动[防空]仅需弃置一张牌。",
        zhudaojiandui: "柱岛舰队", "zhudaojiandui_info": "锁定技,每当你使用或打出一张非虚拟非转化的基本牌,你获得一个[柱]标记。你可以移去三个柱标记视为使用一张不计入次数限制的杀。",
        sawohaizhan: "萨沃海战", "sawohaizhan_info": "每回合各限一次。你可以将一张红牌当作洞烛先机使用,你可以将一张黑牌当作雷杀使用。",
        sawohaizhan_1: "雷杀", "sawohaizhan_1_info": "你可以将一张黑牌当作雷杀使用。",
        sawohaizhan_2: "洞烛先机", "sawohaizhan_2_info": "你可以将一张红牌当作洞烛先机使用（洞烛先机：观星2,然后摸两张牌）。",
        qingyeqingyeqing: "青叶青叶青", "qingyeqingyeqing_info": "当你成为牌的唯一目标时,你可以指定一名其他角色,其可以选择弃置一张非基本牌令此牌对你无效。",
        mingyundewufenzhong: "命运的五分钟", "mingyundewufenzhong_info": "你可以跳过判定和摸牌阶段,视为使用一张雷杀或火杀,你可以弃置一张装备牌并跳过出牌阶段,视为使用一张雷杀或火杀,你可以跳过弃牌阶段并翻面,视为使用一张雷杀或火杀。",
        wufenzhong1: "命运的五分钟", "wufenzhong1_info": "你可以跳过判定和摸牌阶段,视为使用一张雷杀或火杀",
        wufenzhong2: "命运的五分钟", "wufenzhong2_info": "你可以弃置一张装备牌并跳过出牌阶段,视为使用一张雷杀或火杀",
        wufenzhong4: "命运的五分钟", "wufenzhong4_info": "你可以跳过弃牌阶段并翻面,视为使用一张雷杀或火杀。",
        qijianshashou: "旗舰杀手", "qijianshashou_info": "出牌阶段限一次,你可以与一名角色进行拼点,若你赢,本回合你与该角色距离视为1,你对该目标使用杀无次数限制且伤害+1,若你没赢,你跳过出牌阶段和弃牌阶段。",
        qijianshashou_1: "旗舰杀手", "qijianshashou_1_info": "",
        zhanxianfangyu: "战线防御", "zhanxianfangyu_info": "每名角色回合限一次,若你没有装备防具,你成为黑色杀的目标时,取消之。每回合限一次,距你为1的角色成为杀的目标时,你可以弃置一张牌并代替该名角色成为此杀的目标。",
        zhanxianfangyu1: "战线防御", "zhanxianfangyu1_info": "",
        Zqujingying: "Z驱菁英", "Zqujingying_info": "出牌阶段限一次,你可以把任意张牌交给等量名角色,获得牌的角色依次选择:其交给你一张牌作为Z或令你获得其两张牌。",
        Z_qianghua: "Z强化", "Z_qianghua_info": "出牌阶段,你可以移去一张Z,强化一项。(全局强化关闭时仍有效)",
        huhangyuanhu: "护航援护", "huhangyuanhu_info": "其他角色成为杀的唯一目标时,你可以交给其一张牌并获得其区域内的一张牌；当你成为杀的唯一目标时,你可以选择一名目标,其可以选择交给你一张牌并获得你区域内的一张牌",
        shizhibuyu: "矢志不渝", "shizhibuyu_info": "当你受到伤害时,你可以弃置两张颜色相同的牌令此伤害-1。你受到伤害时进行判定,若结果为红色,你摸一张牌,黑色,你弃置一名角色的一张牌。 当你的判定牌生效后,你可以令一名角色使用杀次数+1和手牌上限+1直到你的下回合开始。",
        shizhibuyu1: "矢志不渝", "shizhibuyu1_info": "",
        shizhibuyu1_eff: "矢志不渝", "shizhibuyu1_eff_info": "直到回合结束,手牌上限+1,出杀次数+1",
        qianxingtuxi: "潜行突袭", "qianxingtuxi_info": "你使用牌无视距离限制；若你在出牌阶段以外造成伤害,你于此轮获得规避且受到伤害的角色下个回合第一次造成伤害时须进行一次判定,如果为黑桃,此次伤害-1。",
        qianxingtuxi_debuff: "被袭", "qianxingtuxi_debuff_info": "锁定技,你第一次造成伤害时须进行一次判定,如果为黑桃,此次伤害-1。",
        "31jiezhongdui": "31节中队", "31jiezhongdui_info": "每回合限一次,有角色使用杀指定目标后,若其体力值小于等于目标,你可以选择一项:1令此杀不可响应;2令此杀伤害+1;3令当前回合角色摸一张牌。",
        jujianmengxiang: "巨舰梦想", "jujianmengxiang_info": "出牌阶段,你可以失去一点体力,视为使用一张基本牌或非延时锦囊牌（每回合每种牌名限一次）。",
        sidajingang: "四大金刚", "sidajingang_info": "你使用杀造成伤害后,你可以与目标拼点,若你赢你获得其一张牌。你发动[远航摸牌]后可以摸一张牌。",
        jiujingzhanzhen: "久经战阵", "jiujingzhanzhen_info": "出牌阶段限两次,你可以重铸一张红牌。结束阶段,你可以选择X名角色,其各选择一项:1摸一张牌,2令你获得一点护甲(至多为一)。X为你本回合弃置的红牌数。",
        wuweizhuangji: "无畏撞击", "wuweizhuangji_info": "限定技,出牌阶段,若你的体力值最少,你可以失去所有体力（至少一点）,然后对一名角色造成x点伤害(x为你当前的体力上限)",
        zhongzhuangcike: "重装刺客", "zhongzhuangcike_info": "你装备区内有牌时,你使用的杀无视防具；你即将造成的伤害视为体力流失",
        duomianshou: "多面手", "duomianshou_info": "出牌阶段限三次,你可以弃置一张手牌,视为使用一张牌堆中点数相同的不同类型的牌(不受次数限制）,若牌堆中没有相同点数的牌名,重置该技能发动次数,且本回合不能再使用该点数发动技能.",/*每回合限一次,你对其他中小型船使用转化牌时,其选择弃置一张牌或令你摸一张牌。*/
        duomianshou_1: "多面手", "duomianshou_1_info": "每回合限一次,你对其他中小型船使用转化后的牌时其选择一项：1弃置一张牌,2令你摸一张牌。",
        kaixuan: "凯旋", "kaixuan_info": "你使用杀指定唯一目标时,你可弃置一张牌,令此杀伤害+1。",
        changge: "长歌", "changge_info": "锁定技,你使用杀即将造成的伤害≥2时,或你的体力值≤2时,你的杀无视防具。",
        xiongjiaqibin: "胸甲骑兵", "xiongjiaqibin_info": "锁定技,你计算与座次比你靠后的角色距离-1。",
        yishisheji: "意式设计", "yishisheji_info": "每轮限一次,你首次成为其他角色普通锦囊牌或杀的目标时,取消之。你使用杀指定唯一目标时可以进行判定,若判定结果不为红桃,此杀基础伤害+1,否则此杀无效。",//每轮限一次,你可以免疫一次牌造成的伤害。
        jueshengzhibing: "决胜之兵", "jueshengzhibing_info": "你使用杀指定有护甲的目标时,你可以弃置其一张牌；你使用锦囊牌时,你可以摸一张牌。若你以此法摸或弃置了总计两张牌,此技能本回合失效,反之,回合结束时你获得[智愚]直到下回合开始。",
        zhanfu: "战斧", "zhanfu_info": "你手牌数为场上最多时,你使用杀无视距离",
        xinqidian: "新起点", "xinqidian_info": "出牌阶段限一次,你可以选择至多3名角色,你与这些角色各展示一张牌:若展示的牌花色均不相同,每人摸1张牌;否则,参与展示牌的角色计算与其他角色距离-1直至其的下个回合结束。",
        jilizhixin: "激励之心", 'jilizhixin_info': "若你的宝物栏为空,你视为装备着'侦察机'。你可以弃一张牌并跳过出牌阶段,令一名角色获得一个额外回合。",
        hangkongzhanshuguang: "航空战曙光", "hangkongzhanshuguang_info": "出牌阶段限一次,你可以令一名角色摸一张牌。若目标是航母,改为摸两张牌。",

        jifu_R_weicheng: "未成", 'jifu_R_weicheng_info': "锁定技,你的手牌上限+1。准备阶段你进行判定,若结果为红色：你回复一点体力,摸一张牌。若结果为黑色,你流失一点体力。",
        jifu_R_yuanjing: "愿景", 'jifu_R_yuanjing_info': "觉醒技,当你进入濒死时,体力上限+1,将体力恢复至上限,然后失去未成",
        jifu_R_lingwei: "领卫", 'jifu_R_lingwei_info': "当有角色使用伤害类牌指定唯一目标时,你可以弃置一张牌,然后选择一项：1、令此牌伤害+1。2、此牌无法被响应。若此牌的使用者是驱逐或S国船,则你与此牌的使用者各摸一张牌。（若此牌的使用者是你自己,则只摸一张牌）若因“领卫”技能效果造成了伤害,则本轮失去“领卫”。",
        jifu_R_yuanqin: "远亲", 'jifu_R_yuanqin_info': "锁定技,塔什干与I国船使你回复体力时,回复的体力值+1。",
        u81_langben: "狼奔", u81_langben_info: "你可以将一张非基本牌交给本回合未以此法选择过的角色,令其他角色计算与其的距离为1直到其下个回合开始时。",
        u81_langben_target: "狼奔目标", u81_langben_target_info: "其他角色计算与你距离为1。",
        u47_xinbiao: "信标", u47_xinbiao_info: "有角色体力值减少后,你可以弃置一张黑色牌并记录该角色当前的体力值与手牌数。每个势力只能有一名角色被记录。",
        u47_xinbiao_hp: "信标", u47_xinbiao_hp_info: "信标",
        u47_xinbiao_cards: "信标", u47_xinbiao_cards_info: "信标",
        u47_huxi: "虎袭", u47_huxi_info: "出牌阶段限一次,你可以将一名被记录的角色的体力值和手牌数调整为记录值,然后摸一张牌并移除记录,",
        u81_zonglie_shanghai: "纵猎", u81_zonglie_shanghai_info: "",
        u81_zonglie: "纵猎", u81_zonglie_info: "每回每名角色限一次,你对其他角色造成伤害时,若其手牌与你不相等,其可以交给你一张手牌并摸一张牌,防止此伤害,如此做,其本回合不能响应你的牌。",
        u81_xunyi: "巡弋", u81_xunyi_info: "每回合限一次,你的攻击范围内,有角色在回合外获得牌时,若其不处于濒死状态,你可以令全场角色选择是否对其使用一张牌。",
        z1_Zqulingjian: "Z驱领舰", "z1_Zqulingjian_info": "当G国驱逐舰受到/造成伤害后,你可以将造成伤害的牌置于武将牌上称为“Z”。有其他角色受到雷属性伤害时,你可以弃置一张“Z”,令此伤害-1；当你造成雷属性伤害时,你可以弃置一张“Z”,令此伤害+1。准备阶段,你可以移动一张“Z”。(全局)有Z的角色受到伤害时,可以移去所有Z,防止此伤害。",
        z1_Zqulingjian_draw: "Z驱领舰_摸牌", "z1_Zqulingjian_draw_info": "出牌阶段,你可以移去你武将牌上任意张z并令一名角色摸等量的牌。",
        z1_Zqulingjian_source: "Z驱领舰_加伤", "z1_Zqulingjian_source_info": "当你造成雷属性伤害时,你可以弃置一张“Z”,令此伤害+1。",
        z1_Zqulingjian_damage: "Z驱领舰_减伤", "z1_Zqulingjian_damage_info": "有其他角色受到雷属性伤害时,你可以弃置一张“Z”,令此伤害-1。",
        z1_Zqulingjian_move: "Z驱领舰_移动Z", "z1_Zqulingjian_move_info": "准备阶段,你可以移动一张“Z”。",

        z16_shuileibuzhi: "水雷布置", z16_shuileibuzhi_info: "出牌阶段限一次,你可以将一张手牌置于一名角色的武将牌上,称为Z。(全局)判定阶段开始时,你可以弃置一张Z,然后执行一次兵粮寸断判定。",
        z16_lianhuanbaopo: "连环爆破", z16_lianhuanbaopo_info: "出牌阶段限一次,你可以从下家开始将除你外的所有角色武将牌上的z当作雷杀对其使用。",
        //z16_lianhuanbaopo: "连环爆破", z16_lianhuanbaopo_info: "你的黑色【杀】可以当做【雷杀】使用,你的其他黑色牌可以当做【杀】使用或打出,你使用【雷杀】时无距离次数限制防具。",
        //z16_lianhuanbaopo_sha: "黑牌当杀", z16_lianhuanbaopo_sha_info: "你的黑色牌可以当做【杀】使用或打出",
        //z16_shuileibuzhi: "水雷布置", z16_shuileibuzhi_info: "当你每回合第一次造成伤害时,你可以将牌堆顶的一张牌置于武将牌上,称为Z。出牌阶段,你可以将一张Z当作兵粮寸断使用。(全局)有Z的角色准备阶段,可以弃置一张Z并弃置判定区内所有与此牌花色相同的牌。",
        //z16_shuileibuzhi_bingliang: "兵粮寸断", z16_shuileibuzhi_bingliang_info: "出牌阶段,你可以将一张Z当作兵粮寸断使用。",
        Z_judge: "水雷布置",
        z18_weisebaoxingdong: "威瑟堡行动", z18_weisebaoxingdong_info: "每回合限一次,你可以将至多两张手牌置于等量角色的武将牌上,称为Z。出牌阶段,你可以移去一张Z,观看一名角色的手牌,然后视为使用一张火攻。(全局)武将牌上有Z的角色出牌阶段使用杀的次数+1；使用与Z中包含类型相同的牌时须弃一张牌(没有则不弃),然后可以弃置一张与使用的牌相同牌名的Z。",
        z18_weisebaoxingdong_huogong: "火攻", z18_weisebaoxingdong_huogong_info: "你可以移去一张Z,观看一名角色的手牌,然后视为使用一张火攻。",
        z17_naerweikejingjie: "纳尔维克警戒", z17_naerweikejingjie_info: "出牌阶段,你可以将任意张牌置于武将牌上,称为Z,然后将一名角色至多等量张牌置于其武将牌上,也称为Z。(全局)对有Z的角色造成伤害时,可以摸一张牌。",
        z21_tuxi: "突袭", z21_tuxi_info: "出牌阶段开始时,你可以选择攻击范围内的一名角色,将其一张牌置于你的武将牌上,称为Z。（全局）若你有Z,你使用牌指定其他角色为目标后,你可以令其随机弃置一张牌,然后移去一张Z",
        z22_tuxixiawan: "突袭峡湾", z22_tuxixiawan_info: "出牌阶段开始时,你可以将任意角色一张牌置于自己的武将牌上,称为Z。(全局）其他角色造成伤害后,若你有Z,你可以移去一枚Z,进行一次判定,令当前回合角色不能使用或打出与判定牌颜色相同的牌直到回合结束。",
        cardsDisabled_color: "不能使用_颜色", cardsDisabled_color_info: "你不能使用或打出对应颜色的手牌。",
        matapanjiaozhijian: "马塔潘角之箭", matapanjiaozhijian_info: "你使用锦囊牌指定目标后,你可以弃置任意张牌,令等量目标不可响应此牌。",
        zhongbangtuxi: "重磅突袭", zhongbangtuxi_info: "限定技,出牌阶段,你可以弃置任意张红色牌对等量角色各造成一点火焰伤害。",
        huangjiahaijunderongyao: "皇家海军的荣耀", huangjiahaijunderongyao_info: "锁定技,你对其他角色造成伤害或受到其他角色的伤害时,你弃置对方的一张牌,若此牌点数小于等于受伤角色的手牌数,此伤害+1",
        huangjiaxunyou: "皇家巡游", huangjiaxunyou_info: "锁定技,你计算与其他角色距离-1.",
        tianshi: "天使", tianshi_info: "主公技,你的判定牌生效前,E国势力的角色可以打出一张手牌代替之",
        tianshi2: "天使2", tianshi2_info: "拥有“天使”的角色判定牌生效前,E国势力的角色可以打出一张手牌代替之",
        jishiyu_R: "及时雨", jishiyu_R_info: "每回合限三次,若你的体力值全场最少,你的判定牌生效后,你可以获得之。",
        jishiyu_R1: "及时雨", jishiyu_R1_info: "每回合各限一次,当你需要使用或打出杀时,你可以进行判定,判定结果为黑色则视为你使用或打出了杀。",
        yongbuchenmodezhanjian: "永不沉没的战舰", yongbuchenmodezhanjian_info: "主公技,每回合限一次,你有护甲值时,你可以弃置一张牌令受到的伤害-1。",
        xiuqi: "修葺", xiuqi_info: "当你发动军辅将牌交给一名其他角色时,你可以令其获得以下效果：你首次造成伤害时,可以回复一点体力。直到其回合结束。",
        xiuqi2: "修葺", xiuqi2_info: "每回合限一次,你造成伤害时可以回复一点体力。",
        wanbei: "完备", wanbei_info: "锁定技,你获得开幕航空,你的开幕航空无法升级。你的手牌上限+X,X为你发动军辅置于武将牌上的牌的数量",
        //iuqi2: "修葺2", xiuqi2_info: "下一次发动开幕航空的技能等级+1",
        tiaobangzuozhan: "跳帮作战", tiaobangzuozhan_info: "出牌阶段限一次,你可以视为对一名角色使用决斗。若你以此法造成伤害,你观看其手牌并获得其区域内一张牌；若你因此受到伤害,你令其获得你一张手牌,然后防止此伤害。",
        baixiang: "白象", baixiang_info: "锁定技,你无法使用防具牌。当你受到雷属性伤害时,防止之。",
        guochuan: "过穿", guochuan_info: "锁定技,你受到伤害时,你可以弃置一张防具牌或失去一点体力防止此伤害。然后你可以选择一名与你距离为一的角色(不能是伤害来源),令其承受此伤害并摸伤害值张牌。",
        zuihouderongyao: "最后的荣耀", zuihouderongyao_info: "锁定技,摸牌阶段开始时,你选择以下一项：1,多摸一张牌且你的攻击范围-1。2,你的攻击范围+1。你的攻击范围+2X。(X已阵亡角色数)",
        '29jienaerxun': "29节纳尔逊", '29jienaerxun_info': "当你本回合内第一次使用“杀”指定目标时,若你的攻击范围大于3,此杀不可响应。",/* 若你的体力为全场最高时,此杀伤害+1。 */
        zuihouderongyao_less: "少摸加距离",
        zuihouderongyao_more: "多摸减距离",
        hongseqiangwei: "红色蔷薇", hongseqiangwei_info: "你使用伤害类牌后,可以将一张手牌置于武将牌上称为[花],然后摸一张牌。[花]包含对应座次（点数超出游戏人数则减去游戏人数）的角色受到伤害时,你须弃置一张对应点数的[花]并防止此伤害。",
        bujushenfeng: "不惧神风", bujushenfeng_info: "当你受到伤害时,你可以获得造成伤害的牌。你的手牌上限基数为你的体力上限。",
        shenfeng: "神风", shenfeng_info: "当你造成或受到一点伤害时,你获得一个“风”标记。",
        buju: "不惧", buju_info: "每轮各限一次,你可以移去一个“风”视为使用酒或无懈可击。 以此法使用的无懈可击结算后,你重置[援军]。",
        qiangyun: "强运", qiangyun_info: "觉醒技,当你进入濒死时,恢复一点体力。",
        yuanjun: "援军", yuanjun_info: "限定技,若你有至少6个“风”标记,你可以移去所有“风”视为使用万箭齐发。",
        buju_wuxie: "不惧_无懈", buju_wuxie_disable: "无懈_不可用",
        buju_jiu: "不惧_酒", buju_jiu_disable: "酒_不可用",
        liaowangtai: "瞭望台", liaowangtai_info: "锁定技,你计算与其他角色的距离-2。出牌阶段,你可以视为对距离为1的目标使用一张火攻并摸X张牌,若此做,你计算与其他角色的距离+X,(X为你使用此法的次数)",
        jingruizhuangbei: "精锐装备", jingruizhuangbei_info: "当你装备武器时,你使用射击造成伤害时可以摸一张牌；当你使用射击指定目标时,你可以进行一次判定,若与此“射击”颜色相同,则你可以额外指定一个目标",
        jingruizhuangbei_mopai: "精锐装备_摸牌",
        jingruizhuangbei_fencha: "精锐装备_分叉",
        dananbusi: "大难不死", dananbusi_info: "限定技,当你受到的伤害不小于你当前体力值时,你可以防止之。",
        houfu: "后福", houfu_info: "出牌阶段限一次,你可以选择一名其他角色,其选择一项:1视为对你使用一张杀(无距离限制),2令你从牌堆中获得一张基本牌。",
        zhanliexianfuchou: "战列线复仇", zhanliexianfuchou_info: "每回合限一次,你造成的伤害+X,X=你本轮受到伤害的次数",
        pingduzhanhuo: "平度战火", pingduzhanhuo_info: "结束阶段,若你本回合未造成伤害,你摸一张牌；准备阶段,若你自上个结束阶段起未受到伤害,你摸一张牌",
        mujizhengren: "目击证人", mujizhengren_info: "限定技,出牌阶段,你可以弃置3张手牌,然后令一名角色翻面。",
        shixiangquanneng: "十项全能", shixiangquanneng_info: "锁定技,你的舰种技能无法升级,每轮开始时,你失去以此法获得的技能,然后从以下技能中选择一项获得：1、防空,2、开幕航空,3、军辅",
        pangguanzhe: "旁观者", pangguanzhe_info: "锁定技,你的回合开始时,失去上回合以此法获得的技能,随机获得在场角色武将牌上的一个技能。若该技能带有判定,你可以选择判定结果。(远航,强化,航母,战列,巡洋,驱逐,潜艇,开幕航空,火控雷达,先制鱼雷,十项全能,挑战装备除外;主公技,限定技,使命技,觉醒技除外;绝境逢生除外。)",
        hangkongyazhi: "航空压制", "hangkongyazhi_info": "限定技,你可以失去开幕航空,令一名角色失去所有护甲且本轮技能失效。",
        chuansuohongzha: "穿梭轰炸", "chuansuohongzha_info": "每轮限一次,其他角色使用伤害类牌结算结束后,若你未受伤,你可以获得此牌对应的所有实体牌。每回合限一次,你使用的伤害类牌结算结束后,你可以将其交给一名未受伤角色。",
        chuansuohongzha_get: "穿梭轰炸", "chuansuohongzha_get_info": "每轮限一次,其他角色使用伤害类牌结算结束后,若你未受伤,你可以获得此牌对应的所有实体牌。",
        chuansuohongzha_send: "穿梭轰炸", "chuansuohongzha_send_info": "每回合限一次,你使用的伤害类牌结算结束后,你可以将其交给一名未受伤角色。",
        hangkongyazhi_fengyin: "航空压制_封印",
        yuanyangpoxi: "远洋破袭", "yuanyangpoxi_info": "锁定技,你使用锦囊牌对攻击范围内的角色造成伤害+1；你出牌阶段使用杀的次数-1.",
        juejingfengsheng: "绝境逢生", juejingfengsheng_info: "每轮开始时或你进入濒死状态时,你可以弃置任意张未记录点数的牌并记录其点数,然后你获得X点体力上限并恢复X点体力,摸X张牌（X为以此法弃置的手牌数量）",
        saqijian: "萨奇剪", "saqijian_info": "你获得【防空】。你可以将一张黑色牌当无懈可击使用。当你使用【开幕航空】或【防空】后,你获得一张【影】（黑桃A）。",
        jupaohuoli: "巨炮火力", "jupaohuoli_info": "你使用杀造成伤害时,若你手牌数大于目标手牌数,此伤害+1。",
        guanjianyiji: "关键一击", "guanjianyiji_info": "每回合对每名角色限一次,你使用牌指定目标后,你可以扣置目标的一张牌于武将牌上,其准备阶段开始时获得之。若目标为战列舰,不计入发动次数限制。",
        duikongzhiwei: "对空直卫", "duikongzhiwei_info": "每轮限一次,当一名角色使用锦囊牌指定至少两名角色为目标时,你可以弃置一张牌,令此牌对你和距离1的角色无效。",
        bigseven: "BIGSEVEN", "bigseven_info": "你使用基本牌和非延时锦囊牌指定唯一目标后,可以进行判定。若结果与使用的牌类型相同,你可以额外指一名角色为目标。(场上每有一名自己以外拥有bigseven的角色,目标+1)",
        saobaxing: "扫把星", "saobaxing_info": "锁定技,每回合限一次,当一名角色的判定牌生效前,若判定结果为红色,你须令其重新判定。",
        //第一次配音到这里
        shaojie: "哨戒", "shaojie_info": "锁定技,你无法打出闪响应万箭齐发/近距支援。当你受到万箭齐发/近距支援伤害时,你获得一点护甲。",
        zhiyu_R: "智愚", "zhiyu_R_info": "当你受到伤害后你可以摸一张牌,然后展示所有手牌。若颜色均相同,你令伤害来源弃置一张手牌。",
        beihaidandang: "被害担当", "beihaidandang_info": "每回合限一次,其他角色受到伤害时,你可以代替其受此伤害,然后摸x张牌,将x张手牌交给一名其他角色或弃置(x为你已损失的体力值)。若目标为航母,此伤害值-1。",
        xingyundeyunyuqu: "幸运的云雨区", "xingyundeyunyuqu_info": "结束阶段,你可以将一张牌当作乐不思蜀对自己使用然后恢复一点体力,然后将手牌摸至体力上限(至多为5)。你的判定区有牌时计算与其他角色距离+1。",
        diwuzhandui: "第五战队", "diwuzhandui_info": "准备阶段,你可以展示牌顶堆X张牌,你可以使用其中一张牌,若你在结算过程中造成了伤害,你可以将剩余的牌交给任意角色。（X为场上巡洋舰数量且至多为3）",
        bisikaiwanshoulie: "比斯开湾狩猎", "bisikaiwanshoulie_info": "当你一次性失去两张牌时,你可以令任意名角色各摸一张牌",
        maliyanaliehuoji: "马里亚纳猎火鸡", "maliyanaliehuoji_info": "每名角色的弃牌阶段结束时,你可以本阶段进入弃牌堆的牌中选择至多3张牌,令一名其他角色用自己区域内任意张花色数相等的牌置换之。若其置换后手牌数增加,则其受到X点火属性伤害,X=增加的手牌数。",
        tebiekongxi: "特别空袭", "tebiekongxi_info": "转换技,阳:你的回合外；阴:你的回合内,当你因使用打出或弃置而一次性失去两张或更多牌时,你可以将其中一张牌置于武将牌上,称为“战”(至多三张)。你可以将“战”当作无懈可击使用或如手牌般使用打出。",
        beijixingweishe: "北极星威慑", "beijixingweishe_info": "你使用杀对其他角色造成伤害后,目标不能使用或打出杀直到其回合结束。",
        beijixingweishe_effect: "北极星威慑效果", "beijixingweishe_effect_info": "不能使用或打出杀直到回合结束。",
        jianduixunlian: "舰队训练", "jianduixunlian_info": "出牌阶段限一次,你可以观看一名角色的手牌,然后交换一种花色的所有牌。",
        aizhi: "爱知", "aizhi_info": "出牌阶段限一次,你可以观看并弃置你攻击范围外玩家的一张手牌,若为锦囊牌此技能视为未发动过。然后你可以弃置一张牌,视为使用之。",
        longgu: "龙崮", "longgu_info": "你存活时,与你同势力的角色和主公准备阶段时,可以跳过摸牌阶段并选择一项：不能成为基本牌/普通锦囊牌和延时锦囊牌的目标,直至其下一次使用基本牌/普通锦囊牌和延时锦囊牌。",
        longgu_skill: "龙崮", "longgu_skill_info": "准备阶段时,你可以跳过摸牌阶段并选择一项：1,不能成为基本牌的目标，直至其下一次使用基本牌;2,不能成为普通锦囊牌和延时锦囊牌的目标,普通锦囊牌和延时锦囊牌。",
        longgu_basic: "龙崮_基本", "longgu_basic_info": "锁定技,你不能成为基本牌的目标,直至其下一次使用基本牌。",
        longgu_trick: "龙崮_锦囊", "longgu_trick_info": "锁定技,你不能成为锦囊牌和延时锦囊牌的目标,直至其下一次使用普通锦囊牌和延时锦囊牌。",
        jianghun: "江魂", "jianghun_info": "你阵亡时,令其他角色与全部C势力计算距离时始终+1。",
        zhizhanzhige: "止战之戈", "zhizhanzhige_info": "结束阶段,你可以依次视为使用至多三张本回合出牌阶段使用的基本牌或普通锦囊牌,然后翻面。",
        zhongleizhuangjiantuxi: "重雷装舰突袭", "zhongleizhuangjiantuxi_info": "限定技,准备阶段若你体力值为一,你可以视为对一名角色使用三张无次数限制的雷杀,若此技能结算流程中目标未进入过濒死状态,你弃置所有手牌与装备牌",
        jianjianleiji: "渐减雷击", "jianjianleiji_info": "每回合限一次,你可以将一张装备牌当作无距离次数限制的雷杀使用",
        fenzhandaodi: "奋战到底", "fenzhandaodi_info": "你的手牌上限基数为你的体力上限。你可以将红色牌当作雷杀使用。你使用杀指定的目标不能使用花色与此杀相同的牌响应。",
        huofu: "祸福", "huofu_info": "锁定技,若你于回合内弃置了红色基本牌,则防止你受到由红色牌造成的伤害直至你下回合开始。",
        xunqian: "巡潜", "xunqian_info": "你使用锦囊牌时,你可以摸一张牌,然后你选择：1.弃置一张牌；2.将任意张牌交给一名其他角色。",
        jinyangmaozhishi: "金羊毛之誓", "jinyangmaozhishi_info": "限定技,当你成为其他角色使用牌的目标时,若你已受伤,你可以令此牌对你无效。",
        zhengzhansihai: "征战四海", "zhengzhansihai_info": "每回合限一次,当你造成或受到伤害后,你可以摸x张牌,x为你已损失的体力值。",
        shuqinzhiyin: "竖琴之音", "shuqinzhiyin_info": "每轮限一次,其他角色技能结算后,你可以弃置两张牌,重置一名其他角色武将牌上的技能,然后其回复一点体力",
        yixinyiyi: "一心一意", "yixinyiyi_info": "出牌阶段限X次,你可以将一张手牌当作雷杀使用,此法使用的牌无次数限制。X为主公已损失体力值。",
        buxiuzhanshi: "不朽战士", "buxiuzhanshi_info": "出牌阶段限一次,你可以弃置任意张牌,视为对等量名角色使用决斗。下个回合摸牌阶段,你的摸牌数量+x（x为你本回合以此法对其他角色造成的伤害数）",
        hailangchuji: "海狼出击", "hailangchuji_info": "有潜艇使用雷杀指定其他角色为目标后,你可以摸一张牌。",
        yangwangxingkong: "仰望星空", "yangwangxingkong_info": "限定技,你可将一张手牌交给一名角色,然后该名角色选择一项：1,弃置所有手牌,2,将血量调整至濒死状态。",
        //_draw: "仰望星空", "yangwangxingkong_draw_info": "你在摸牌阶段的摸牌数-1。",
        yangwangxingkong_card: "弃置所有手牌",
        yangwangxingkong_hp: "失去所有体力",
        zhengzhansifang: "征战四方", "zhengzhansifang_info": "你受到伤害后,你可以从获得牌堆中你选择的类型的一张牌。",
        binghaihuhang: "冰海护航", "binghaihuhang_info": "装备区有牌的角色不能响应你使用的杀。",
        zhuangjiajiaban: "装甲甲板", "zhuangjiajiaban_info": "当你受到伤害时,你可以进行一次判定,若判定结果为红色则防止此伤害。",
        xiandaihuagaizao: "现代化改造", "xiandaihuagaizao_info": "结束阶段,你可以弃x张牌并回复一点体力或体力上限,若你以此法回复体力后体力上限不小于5,则你翻面并恢复一点体力,然后获得*先进空管（x为游戏轮数且至多为3）（先进空管当你使用杀或伤害类锦囊牌时,可受到一点伤害并重复执行一次此牌。）",
        xianjinkongguan: "先进空管", "xianjinkongguan_info": "当你使用杀或伤害类锦囊牌时,可失去一点体力并重复执行一次此牌。",
        zhanxianyuanhu: "战线援护", "zhanxianyuanhu_info": "游戏开始时,你选择一名角色,其受到伤害时防止之,改为你受到此伤害值-1的伤害。",
        //第二次配音到这里

        pachina_R_xinao: "嬉闹", "pachina_R_xinao_info": "你受到伤害后,可以将任意张手牌交给一名其他角色并记录,然后你翻面。若如此做,你回复X点体力。(x为你交出的手牌数/2向下取整)。你翻面后,你可以获得嬉闹对象区域内的一张牌。",
        pachina_R_xinao_back: "嬉闹",
        loki_R_xiance: "献策", "loki_R_xiance_info": "你拥有决策：出牌阶段限一次,你可以将两张手牌当作一张基本牌或非延时锦囊牌使用,本局每种牌名的牌限一次。每轮限一次,其他角色的出牌阶段开始时,你可以交给其两张牌并令其本阶段获得“决策”。本阶段结束时,若其没有杀死过角色,则你对其造成一点伤害。",
        loki_R_xiance2: "决策", "loki_R_xiance2_info": "出牌阶段限一次,你可以将两张手牌当作一张基本牌或非延时锦囊牌使用,本局每种牌名的牌限一次。",
        loki_R_xiance3: "献策",
        loki_R_xiance4: "献策",
        southdakota_R_gumei: "蛊魅", "southdakota_R_gumei_info": "其他角色出牌阶段限一次,其可以选择除你以外的一名角色并交给你一张牌,若如此做,视作你对选择的角色使用一张“决斗”。如果你因此技能造成伤害,此技能失效直到本轮结束。",
        southdakota_R_gumei_phaseUse: "蛊魅_出牌阶段", "southdakota_R_gumei_phaseUse_info": "出牌阶段限一次,你可以选择除蛊魅拥有者以外的一名角色并交给拥有者一张牌,若如此做,视作拥有者对选择的角色使用一张“决斗”。",
        southdakota_R_jianmiemoshi: "歼灭模式", "southdakota_R_jianmiemoshi_info": "你的回合内,其他角色无法对非“歼灭”牌进行响应。回合结束时,你的手牌标记为“歼灭”牌。",
        southdakota_R_zhaopin: "招聘", "southdakota_R_zhaopin_info": "限定技,主公技,你进入濒死状态时,可以弃置自己区域所有牌选择令其他角色依次选择是否响应,若有角色响应,则你与其互换身份牌,然后其可以获得一点体力上限并恢复一点体力,你失去一点体力上限,摸4张手牌,并将体力恢复至1点。",
        huodezhuangbei: "获得装备", "huodezhuangbei_info": "从牌堆中获得一张装备。测试用。",
        zhanxian: "斩仙", "zhanxian_info": "出牌阶段开始前,你可以将任意张手牌作为“斩”扣置在武将牌上,本回合结束时弃置所有“斩”。锁定技,手牌数小于等于你“斩”张数的角色不能响应你使用的牌。你的手牌上限等于体力上限。",
        guishen: "鬼神", "guishen_info": "锁定技,你的出牌阶段内,体力值大于体力上限一半的其他角色所有技能失效。",
        guishen_fengyin: "鬼神_封印",
        sukhbaatar_R_rumeng: "入梦", "sukhbaatar_R_rumeng_info": "锁定技,准备阶段,你选择一名角色与其拼点。你发起拼点或成为拼点目标时可以获得场上一张“军辅”牌。",
        sukhbaatar_R_rumeng_1: "入梦", "sukhbaatar_R_rumeng_1_info": "锁定技,你发起拼点或成为拼点目标时可以获得场上一张“军辅”牌。",
        sukhbaatar_R_sudaren: "苏大人", "sukhbaatar_R_sudaren_info": "转换技,你拼点赢时,转换为阳；拼点没赢,转换为阴。阳：你使用牌时,可以弃置一张“军辅”牌让那张牌额外结算1次。阴：一名角色对你使用牌时,可以摸一张牌,并将一张手牌置于在武将牌上,视作“军辅”牌(至多五张)",
        sukhbaatar_R_zuiqiang: "最强", "sukhbaatar_R_zuiqiang_info": "锁定技,一名武将牌上没有“军辅”牌的其他角色受到你造成的伤害时,若此伤害会令其进入濒死状态,防止之并将你的一张手牌作为“军辅”牌置于其武将牌上。",
        odin_R_ganggenier: "冈格尼尔", "odin_R_ganggenier_info": "准备阶段,依次从牌堆顶给所有没有“军辅”牌的角色武将牌上放置一张牌,视作“军辅”牌。出牌阶段限一次,你可以弃置两名角色各一张“军辅”牌,直到回合结束,其他所有角色无法使用或打出与被以此法弃置的牌相同花色的牌。",
        odin_R_ganggenier_1: "冈格尼尔", "odin_R_ganggenier_1_info": "出牌阶段限一次,你可以弃置两名角色各一张“军辅”牌,直到回合结束,其他所有角色无法使用或打出与被以此法弃置的牌相同花色的牌。",
        vestal_R_mowang: "魔王", "vestal_R_mowang_info": "当有角色陷入濒死时,你可以将自己或其武将牌上的“军辅”牌当做【桃】对其使用。当场上有角色脱离濒死状态时,你可以选择恢复一点体力或摸一张牌。",
        vestal_R_mowang1: "魔王",
        xiwangdeshuguang: "希望的曙光", "xiwangdeshuguang_info": "每个回合结束时,你可以弃置一张手牌,令一名本回合受到过伤害的角色回复一点体力。",
        qiangxiu: "抢修", "qiangxiu_info": "出牌阶段限一次,你可以对一名角色造成一点伤害,然后使其回复一点体力",
        bismarck_R_chajin: "查禁", "bismarck_R_chajin_info": "其他角色于摸牌阶段及“远航”技能效果外从牌堆摸牌时,你可以声明一个花色,之后其可以选择交给你任意张手牌。执行完上述流程后,你可以选择质疑其手牌中还有你声明的花色,然后展示其所有手牌,若其手牌有你声明的花色,你获得之,并对其造成1点伤害；否则,你流失1点体力,并且此技能本轮失效。",
        doubts: "质疑",
        noDoubts: "不质疑",
        bismarck_R_chajin_tempBan: "查禁失效",
        bismarck_R_fanji: "反击", "bismarck_R_fanji_info": "你受到伤害后,你可以对伤害来源使用一张无视距离的【杀】",
        tirpitz_R_jinshu: "禁书", "tirpitz_R_jinshu_info": "每轮开始时,你可以展示一张手牌,并且跳过你本轮的出牌阶段和弃牌阶段。若如此做,每当一张与展示牌花色相同的牌进入弃牌堆时,你摸一张牌。",
        tirpitz_R_chuanyue: "传阅", "tirpitz_R_chuanyue_info": "其他角色准备阶段开始时,你可以展示并交给其一张牌,其本回合无法弃置与展示牌相同花色的牌。",
        tirpitz_R_nvwangfugui: "女王复归", "tirpitz_R_nvwangfugui_info": "觉醒技,场上的“俾斯麦”死亡时,你将体力值调整至1点,获得X点护甲并修改“禁书”（X为因“女王复归”而减少的体力值数量）（修改禁书：每轮开始时,你可以展示一张手牌,若如此做,每当一张与弃置牌花色相同的牌进入弃牌堆时,你摸一张牌。）",
        shuangzi: "双子", shuangzi_info: "转换技,阳：你使用或打出基本牌时摸一张牌；阴：你使用或打出锦囊牌时摸一张牌",
        akagikaga_R_zongyu: "纵欲", akagikaga_R_zongyu_info: "锁定技,你使用【酒】无次数限制,你不能使用【桃】,你可以将【桃】当作【桃园结义】使用。若场上一名角色一轮中成为【酒】【桃】【桃园结义】目标的次数不小于其的体力值时,清空计数,并将其武将牌翻面。",
        akagikaga_R_zongyu_turnOver: "纵欲_翻面",
        savoy_R_xiuzhu: "修筑", savoy_R_xiuzhu_info: "出牌阶段限一次,你可以与一名角色拼点：没有赢的角色,直到回合结束,无法使用或打出与拼点牌相同颜色的牌,若你和其拼点牌点数之和大于13,则你和其各恢复1点体力。",
        savoy_R_wangong: "完工", savoy_R_wangong_info: "觉醒技 结束阶段,若你不为已受伤状态时,你获得技能“装甲”和“要塞群”",
        savoy_R_yaosaiqun: "要塞群", savoy_R_yaosaiqun_info: "你每次进入濒死状态限一次,你可以发动一次“修筑”。",
        cassone_R_yibing: "疑兵", cassone_R_yibing_info: "当你和其他角色进行拼点时,你可以：阳：将自己区域的一张牌移到其他角色相应位置。阴：将其他角色场上一张牌移动到自己相应位置。疑兵处于阴状态时,你参与的拼点,所有人点数视为14-X（X为牌原本的点数）。",
        cassone_R_weizhuangqixi: "伪装奇袭", cassone_R_weizhuangqixi_info: "出牌阶段限一次,你可以与一名角色：若你赢,你与其之间距离视作1,且每回合你对其使用的第一张牌不可响应,直到其回合结束；若其赢,你失去一点体力,那之后,直到其回合结束,你受到其造成的伤害后,恢复1点体力",
        cassone_R_weizhuangqixi_win: "伪装奇袭_赢",
        cassone_R_weizhuangqixi_lose: "伪装奇袭_没赢",
        Xfliegerkorps_R_piaobodeying: "漂泊的鹰", "Xfliegerkorps_R_piaobodeying_info": "游戏开始时,你获得技能“航母”。出牌阶段限一次,你可以与一名角色拼点：若你赢,你获得一枚“鹰”标记,并摸X张牌（X为场上“鹰”标记数量且最多为3）；若你没赢,移去场上所有“鹰”标记,并给其一枚“鹰”标记。拥有“鹰”标记的其他角色若没有技能“航母”,视作拥有和你一样等级的“航母”,否则,摸牌阶段摸牌数+1。",
        Xfliegerkorps_R_piaobodeying_mark: "漂泊的鹰",
        Xfliegerkorps_R_piaobodeying_mark_yingzi: "漂泊的鹰_摸牌+1",
        Xfliegerkorps_R_piaobodeying_mark_hangmucv: "漂泊的鹰_开幕航空",
        huodeyanshi: "获得延时", "huodeyanshi_info": "从牌堆中获得一张延时锦囊牌。测试用。",
        shujuzaisheng: "数据再生",
        shujuzaisheng_info: "锁定技,你始终跳过摸牌阶段,且手牌上限+2。当其他角色的♠牌因弃置或判定而置入弃牌堆时,你可以获得等量的【影】。出牌阶段限一次,你可以弃置至多X张♠牌,然后摸等量的牌。（X为你的体力值）",
        yapogan: "压迫感",
        yapogan_info: "摸牌阶段,你可以少摸任意张牌并获得等量其他角色各一张牌,若获得牌为♠,你须弃置此牌并视为你对对应角色使用一张不计入次数,无视距离的【火杀】。",
        xietongzuozhan: "协同作战",
        xietongzuozhan_info: "出牌阶段限一次,你可以选择任意名角色并展示等量张手牌,目标角色依次为每张手牌从三个随机牌名中选择一个不重复的基本或锦囊牌的牌名。展示的手牌在你的手牌区内视为选择的牌名（进弃牌堆或被其他角色获得时还原）。",
        yamato_R_tongchou: "同仇",
        yamato_R_tongchou_info: "锁定技,游戏开始时,你选择一名其他角色,当其造成伤害后,你受到等量的伤害。每次你的体力变动时,你获得数量为体力变化值两倍的【影】；你的【影】不计入手牌上限。",
        yamato_R_tongchou2: "同仇",
        yamato_R_tongchou2_info: "其他角色受到伤害后,你可以选择受到等量的伤害。每次你的体力变动时,你获得数量为体力变化值两倍的【影】；你的【影】不计入手牌上限。",
        yamato_R_dikai: "敌忾",
        yamato_R_dikai_info: "你可以将任意两张牌当任意一种【杀】使用或打出。",
        yamato_R_dikai2: "敌忾",
        yamato_R_dikai2_info: "你可以将任意两张牌当任意一张基本牌使用或打出。每回合最多通过此法使用一张【桃】。",
        yamato_R_nizhuanfanji: "逆转反击",
        yamato_R_nizhuanfanji_info: "使命技。成功：当“同仇”角色死亡后,你升级技能“同仇”和“敌忾”。失败：当你进入濒死状态时,你将体力回复至1点,然后你可以依次对当前回合角色使用你的手牌（无距离和次数限制）。",

        kelaosaiweici_R_jinji: "进击",
        kelaosaiweici_R_jinji_info: "每回合限一次,你使用【杀】后可以摸一张牌,然后若此牌为基本牌,则你可以弃置之令此【杀】不计入本回合的使用次数。",
        kelaosaiweici_R_lunzhan: "论战",
        kelaosaiweici_R_lunzhan_info: "准备阶段,你可以选择一项：1.观看并排列牌堆顶的4张牌,本回合你的手牌上限+X（X为本局G国角色数）；2.本回合你使用【杀】造成的伤害+1。",
        kelaosaiweici_R_lunzhan_hand: "论战：手牌上限",
        kelaosaiweici_R_lunzhan_damage: "论战：伤害加一",
        jing_shu: "惊鼠", "jing_shu_info": "出牌阶段限一次，你可以展示任意张手牌，然后令一名其他角色选择：1.翻面并获得你展示的所有牌；2.弃置你展示的所有牌，然后交给你等量张牌。",
        ling_mu: "灵目", "ling_mu_info": "摸牌阶段结束时，你可以展示所有手牌，若其中没有锦囊牌，你选择：1.摸两张牌；2.本回合你造成的伤害+1。",
        yuleizhantujin: "鱼雷战突进",
        yuleizhantujin_info: "出牌阶段限一次，你可以亮出牌堆顶X张牌（X为你的装备区牌数与场上驱逐舰数量之和），选择一名角色，你依次对其使用其中可以使用的基本牌（无次数限制），然后其对你使用其中可以使用的普通锦囊牌。",
        zhanduiqijian: "战队旗舰",
        zhanduiqijian_info: "每轮限一次。一名角色的出牌阶段开始时，你可以观看牌堆顶的三张牌，并令其获得其中的0-2张牌。",
        lingjupaoji: "零距炮击",
        lingjupaoji_info: "出牌阶段限一次，你可以选择一名其他角色，展示牌堆顶的三张牌，你可以对其使用其中一张伤害类牌，然后将其余牌置入弃牌堆。本回合你计算与其距离为1。",
        lingjupaoji_1: "零距炮击",
        wuyizhuangji: "无意撞击",
        wuyizhuangji_info: "出牌阶段限一次，你可以失去1点体力，然后对一名其他角色造成其当前体力值一半的伤害（向下取整）。",
        shuileihun: "水雷魂",
        shuileihun_info: "出牌阶段开始时，你可以视为使用一张【雷杀】。",
        shuileiqiangxi: "水雷强袭",
        shuileiqiangxi_info: "出牌阶段，你可以将所有手牌当作一张【雷杀】使用。此【雷杀】需要使用X张【闪】响应且伤害基数+1（X为此牌对应的实体牌数）。然后你结束出牌阶段。",
        shuileiqiangxi_damage: "水雷强袭",
        shuileiqiangxi_damage_info: "",
        shuileiqiangxi_response: "水雷强袭",
        shuileiqiangxi_response_info: "",
        shuileiqiangxi_end: "水雷强袭",
        shuileiqiangxi_end_info: "",
        kongqianyiti: "空潜一体",
        kongqianyiti_info: "锁定技。你于回合内使用基本牌后，从牌堆中获得一张锦囊牌；你于回合外使用锦囊牌后，从牌堆中获得一张基本牌。",
        xiang_busizhishouhu: "不死鸟的守护",
        xiang_busizhishouhu_info: "锁定技，游戏开始时，你获得技能〖守护〗并选择一名其他角色，其获得技能〖守护〗且获得“守护”标记；有守护标记的角色死亡后，你选择一名其他角色，其获得技能〖守护〗且获得“守护”标记。",
        xiang_busizhishouhu_mark: "守护标记",
        xiang_busizhishouhu_mark_info: "",
        xiang_shouhu: "守护",
        xiang_shouhu_info: "锁定技，你的体力上限+1。当你获得此技能后，你摸两张牌并回复1点体力。",
        yuanzhenghuhang: "远征护航",
        yuanzhenghuhang_info: "出牌阶段限一次，你可以将一张手牌置于一名其他角色的武将牌上，称为“护航”牌。其可以如手牌般使用或打出这些牌。当其如此做后，你摸一张牌。",
        yuanzhenghuwei: "远征护卫",
        yuanzhenghuwei_info: "回合开始时，你收回其他角色武将牌上未使用的“护航”牌，然后令这些角色各选择一项：1.下一次使用的牌不可被响应；2.下一次成为牌的目标时取消之。",
        yuanzhenghuwei_directhit: "远征护卫",
        yuanzhenghuwei_directhit_info: "",
        yuanzhenghuwei_evade: "远征护卫",
        yuanzhenghuwei_evade_info: "",
        duomianxunlianjian: "多面训练舰",
        duomianxunlianjian_info: "当你失去牌后，你可以令场上手牌最少的角色摸一张牌。",
        baixue_jiban: "羁绊",
        baixue_jiban_info: "当一名角色受到【杀】或【决斗】造成的伤害时，你可以将一张红桃手牌置于牌堆顶，防止此伤害。若其为驱逐舰，改为任意手牌。",
        qiangxingzhencha: "强行侦查",
        qiangxingzhencha_info: "其他角色的结束阶段，你可以展示其手牌，然后其可以对你使用一张无距离限制的【杀】。若其如此做，你获得其一张手牌。",
        jiquleiji: "甲驱雷击",
        jiquleiji_info: "准备阶段和结束阶段，你可以进行判定，若结果为黑色，你视为使用一张【雷杀】。",

        mijian: "弥坚",
        mijian_info: "当你受到伤害后，你可以选择一项：1.摸两张牌；2.下一张使用的【杀】无法被响应；3.下一次造成的伤害+1；4.获得一点护甲。",
        shanzhan: "善战",
        shanzhan_info: "每轮限X+1次，你可以将一张基本牌当作任意一张基本牌使用或打出（X为你本局累计造成伤害点数）。",
        huixi: "彗袭",
        huixi_info: "出牌阶段开始时，你可以选择一种基本牌或非延时锦囊类型：本回合可将任意一张手牌视为该类型使用一次，且本回合只能使用该类别的牌。",
        huixi_viewas: "慧袭",
        duoneng: "多能",
        duoneng_info: "摸牌阶段，你可以放弃摸牌，改为观看牌堆顶4张牌，获取其中类别各不相同的牌，然后将剩余牌放回牌堆顶。",
        daike: "代课",
        daike_info: "你使用基本牌或普通锦囊结算后，你可以令一名非目标角色摸一张牌，然后弃置一张手牌。",
        xiaoxiao: "枭啸",
        xiaoxiao_info: "锁定技。其他角色对你造成伤害，或你对其他角色造成伤害后，该角色获得1枚「俯冲」标记（有永久免疫者除外）。",
        yingfan: "鹰返",
        yingfan_info: "结束阶段，你可以选择一名有「俯冲」标记的角色，令其选择：①交出所有手牌；②失去1点体力上限并永久免疫枭啸和鹰返效果。",
        yingfan_immune: "永久免疫",
        fuchong: "俯冲",
        xianfeng: "先锋",
        xianfeng_info: "当你使用牌指定目标后，你可以令此牌对其中任意名武将牌未横置的角色无效并横置其武将牌。",
        kuanhuankaimu: "狂欢开幕",
        kuanhuankaimu_info: "出牌阶段，阳：你使场上角色武将牌横置时，你可以摸一张牌。阴：你可以弃置一张牌，然后令一名角色重置其武将牌并摸一张牌。",
        kuanhuankaimu_yin: "狂欢开幕",
        qianzhi: "牵制",
        qianzhi_info: "锁定技。你手牌中的装备牌视为【闪】；回合外，你装备区内的牌无法被获得或弃置；若场上有俾斯麦，你的手牌中的装备牌可当任意基本牌使用或打出。",
        qianzhi_bismark: "牵制",
        beizhai: "北宅",
        beizhai_info: "弃牌阶段，你的黑色手牌不计入手牌数。弃牌阶段结束时，你可以弃置两张黑色手牌，然后从牌堆或弃牌堆随机使用一张装备牌。",
        jidongjiandui: "机动舰队",
        jidongjiandui_info: "锁定技。你的♦基本牌视为♣。你使用黑色【杀】对有防具的角色造成伤害时，该伤害+1。",
        jiangongchuji: "舰攻出击",
        jiangongchuji_info: "当你用【杀】对一名角色造成伤害后，你可以观看其手牌并获得其中一张；若该牌不是黑色，其视为对你使用一张无距离限制的【杀】。",
        modaiqijian: "末代旗舰",
        modaiqijian_info: '当你使用锦囊牌时，若你有"讯"，你获得其中一张；否则你将牌堆顶4张牌中一种颜色的牌作为"讯"扣置于武将牌上，弃置其他牌。',
        haitiantongxun: "海天通讯",
        haitiantongxun_info: '当一名角色的判定牌生效前，你可以打出一张"讯"代替之。当你失去所有"讯"后，你回复1点体力。',
        butaihegedehuwei: "不太合格的护卫",
        butaihegedehuwei_info: "你游戏开始时选择一名角色成为其护卫，每回合限一次，以该角色为目标的牌结算后，你可以令其摸一张牌并展示，然后视为你使用之（不计入上限），若造成体力值变动，你可以更换本技能护卫的目标。",
        nitouchuanlaila: "泥头船来啦",
        nitouchuanlaila_info: "限定技，结束阶段开始时，你可以将区域内所有牌置入弃牌堆，然后选择一名其他角色，该角色区域内每有一张牌与你置入弃牌堆的牌牌名相同，便受到一点伤害。",

        guankanpaidui: "观看牌堆", guankanpaidui_info: "出牌阶段，你可以观看牌堆顶的7张牌。测试用。",

        //新技能翻译写在这上面
        //包名翻译
        jianrbiaozhun: "舰r标准",
        lishizhanyi: '历史战役',
        lishizhanyi_naerweike: '历史战役-纳尔维克',
        lishizhanyi_matapanjiao: '历史战役-马塔潘角',
        lishizhanyi_danmaihaixia: '历史战役-丹麦海峡',
        lishizhanyi_shanhuhai: '历史战役-珊瑚海',
        lishizhanyi_haixiafujizhan: '历史战役-海峡伏击战',
        shixinrumoR: "蚀心入魔",
        shixinrumoR_tan: "蚀心入魔-贪",
        shixinrumoR_chen: "蚀心入魔-嗔",
        shixinrumoR_chi: "蚀心入魔-痴",
        shixinrumoR_man: "蚀心入魔-慢",
        shixinrumoR_yi: "蚀心入魔-疑",
        weijingzhizhi: '未竟之志',
        cangqinghuanying: '苍青幻影',
        shuileizhandui: '水雷战队',
        others: '其他',
    },
};
export { jianrjinji };